# Generated by Django 5.2.1 on 2026-05-06 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IlmiyTadqiqotCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Nomi (En)')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Ilmiy tadqiqot kategoriyasi',
                'verbose_name_plural': 'Ilmiy tadqiqot kategoriyalari',
                'db_table': 'ilmiy_tadqiqot_category',
                'ordering': ['order', 'title_uz'],
            },
        ),
        migrations.CreateModel(
            name='IlmiyTadqiqot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif (En)')),
                ('author_uz', models.CharField(blank=True, max_length=300, verbose_name='Muallif (Uz)')),
                ('author_ru', models.CharField(blank=True, max_length=300, verbose_name='Muallif (Ru)')),
                ('author_en', models.CharField(blank=True, max_length=300, verbose_name='Muallif (En)')),
                ('image', models.FileField(blank=True, null=True, upload_to='ilmiy_tadqiqot/images/%Y/%m/', verbose_name='Asosiy rasm')),
                ('slug', models.SlugField(blank=True, max_length=550, unique=True, verbose_name='Slug')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chiqarilsinmi?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Like soni')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='Komment soni')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tadqiqotlar', to='ilmiy_tadqiqot.ilmiytadqiqotcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Ilmiy tadqiqot',
                'verbose_name_plural': 'Ilmiy tadqiqotlar',
                'db_table': 'ilmiy_tadqiqot',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IlmiyTadqiqotFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(blank=True, max_length=300, verbose_name='Fayl nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Fayl nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Fayl nomi (En)')),
                ('file', models.FileField(upload_to='ilmiy_tadqiqot/files/%Y/%m/', verbose_name='Fayl')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('tadqiqot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ilmiy_tadqiqot.ilmiytadqiqot', verbose_name='Ilmiy tadqiqot')),
            ],
            options={
                'db_table': 'ilmiy_tadqiqot_file',
                'ordering': ['order'],
            },
        ),
    ]
