# Generated by Django 5.1.4 on 2026-04-10 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('question_uz', models.CharField(max_length=500, verbose_name='Savol (Uz)')),
                ('question_ru', models.CharField(blank=True, max_length=500, verbose_name='Savol (Ru)')),
                ('question_en', models.CharField(blank=True, max_length=500, verbose_name='Savol (En)')),
                ('answer_uz', models.TextField(blank=True, verbose_name='Javob (Uz)')),
                ('answer_ru', models.TextField(blank=True, verbose_name='Javob (Ru)')),
                ('answer_en', models.TextField(blank=True, verbose_name='Javob (En)')),
                ('vote_count', models.PositiveIntegerField(default=0, verbose_name='Ovozlar soni')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Javob berilganmi?')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chiqarilsinmi?')),
            ],
            options={
                'verbose_name': 'Savol-javob',
                'verbose_name_plural': 'Savol-javoblar',
                'db_table': 'contact_faq',
                'ordering': ['-vote_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RectorAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=25, verbose_name='Telefon')),
                ('faculty', models.CharField(blank=True, max_length=255, verbose_name="Fakultet / Bo'lim")),
                ('group', models.CharField(blank=True, max_length=50, verbose_name='Guruh raqami')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('message', models.TextField(verbose_name='Murojaat matni')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_review', "Ko'rib chiqilmoqda"), ('answered', 'Javob berildi')], default='new', max_length=20, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Rektorga murojaat',
                'verbose_name_plural': 'Rektorga murojaatlar',
                'db_table': 'contact_rector_appeal',
                'ordering': ['-created_at'],
            },
        ),
    ]
