# Generated by Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='comments',
            field=models.PositiveIntegerField(default=0, verbose_name='Komment soni'),
        ),
        migrations.AddField(
            model_name='faq',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]

