# Generated by Django 5.2.1 on 2026-05-01 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_add_views_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='QabulRaqami',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('label_uz', models.CharField(max_length=200, verbose_name='Nomi (Uz)')),
                ('label_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (Ru)')),
                ('label_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (En)')),
                ('number', models.CharField(max_length=50, verbose_name='Raqam')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Qabul raqami',
                'verbose_name_plural': 'Qabul raqamlari',
                'db_table': 'contact_qabul_raqami',
                'ordering': ['order'],
            },
        ),
    ]
