# Generated by Django 5.2.1 on 2026-05-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_qabul_raqami'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qabulraqami',
            options={'verbose_name': 'Qabul raqami', 'verbose_name_plural': 'Qabul raqamlari'},
        ),
        migrations.RemoveField(
            model_name='qabulraqami',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='qabulraqami',
            name='label_ru',
        ),
        migrations.RemoveField(
            model_name='qabulraqami',
            name='label_uz',
        ),
        migrations.RemoveField(
            model_name='qabulraqami',
            name='order',
        ),
        migrations.AlterField(
            model_name='qabulraqami',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Qabul raqami'),
        ),
    ]
