# Generated by Django 5.2.1 on 2026-05-01 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_simplify_qabul_raqami'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism-familiya')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Murojaat matni')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_review', "Ko'rib chiqilmoqda"), ('answered', 'Javob berildi')], default='new', max_length=20, verbose_name='Holati')),
            ],
            options={
                'verbose_name': 'Aloqa xabari',
                'verbose_name_plural': 'Aloqa xabarlari',
                'db_table': 'contact_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
