# Generated by Django 5.2.1 on 2026-05-01 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_add_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='RectorAppealExtraField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('label_uz', models.CharField(max_length=255, verbose_name='Maydon nomi (Uz)')),
                ('label_ru', models.CharField(blank=True, max_length=255, verbose_name='Maydon nomi (Ru)')),
                ('label_en', models.CharField(blank=True, max_length=255, verbose_name='Maydon nomi (En)')),
                ('field_key', models.SlugField(max_length=100, unique=True, verbose_name='Kalit (field_key)')),
                ('field_type', models.CharField(choices=[('text', 'Matn'), ('textarea', "Ko'p qatorli matn"), ('number', 'Raqam'), ('date', 'Sana'), ('email', 'Email'), ('phone', 'Telefon')], default='text', max_length=20, verbose_name='Tur')),
                ('is_required', models.BooleanField(default=False, verbose_name='Majburiy?')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': "Qo'shimcha maydon",
                'verbose_name_plural': "Qo'shimcha maydonlar",
                'db_table': 'contact_rector_appeal_extra_field',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='rectorappeal',
            name='appeal_type',
            field=models.CharField(choices=[('appeal', 'Murojaat'), ('suggestion', 'Taklif'), ('complaint', 'Shikoyat')], default='appeal', max_length=15, verbose_name='Murojaat turi'),
        ),
        migrations.AddField(
            model_name='rectorappeal',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumotlar"),
        ),
        migrations.AddField(
            model_name='rectorappeal',
            name='sender_type',
            field=models.CharField(choices=[('student', 'Talaba'), ('guest', 'Mehmon')], default='student', max_length=10, verbose_name='Kim yubordi'),
        ),
    ]
