# Generated by Django 5.1.4 on 2026-04-10 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (En)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'db_table': 'students_person_category',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to='persons/%Y/%m/', verbose_name='Asosiy rasm')),
                ('full_name_uz', models.CharField(max_length=255, verbose_name="To'liq ismi (Uz)")),
                ('full_name_ru', models.CharField(blank=True, max_length=255, verbose_name="To'liq ismi (Ru)")),
                ('full_name_en', models.CharField(blank=True, max_length=255, verbose_name="To'liq ismi (En)")),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (En)')),
                ('title_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lavozim (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lavozim (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lavozim (En)')),
                ('position_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy unvon (Uz)')),
                ('position_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy unvon (Ru)')),
                ('position_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ilmiy unvon (En)')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon')),
                ('fax', models.CharField(blank=True, max_length=25, null=True, verbose_name='Faks')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Manzil')),
                ('reception', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qabul vaqti')),
                ('is_head', models.BooleanField(default=False, verbose_name="Bo'lim boshlig'i")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='students.personcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Shaxs',
                'verbose_name_plural': 'Shaxslar',
                'db_table': 'students_person',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PersonContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('content_uz', models.TextField(blank=True, verbose_name='Kontent (Uz)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Kontent (Ru)')),
                ('content_en', models.TextField(blank=True, verbose_name='Kontent (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='students.person', verbose_name='Shaxs')),
                ('tags', models.ManyToManyField(blank=True, related_name='person_contents', to='common.tag', verbose_name='Taglar')),
            ],
            options={
                'verbose_name': 'Shaxs kontenti',
                'verbose_name_plural': 'Shaxslar kontenti',
                'db_table': 'students_person_content',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to='persons/gallery/%Y/%m/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='students.person', verbose_name='Shaxs')),
            ],
            options={
                'verbose_name': 'Shaxs rasmi',
                'verbose_name_plural': 'Shaxs rasmlari',
                'db_table': 'students_person_image',
                'ordering': ['order'],
            },
        ),
    ]
