# Generated by Django 5.1.4 on 2026-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=100)),
                ('title_ru', models.CharField(blank=True, max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='persons/%Y/%m/')),
                ('full_name_uz', models.CharField(max_length=255)),
                ('full_name_ru', models.CharField(blank=True, max_length=255)),
                ('full_name_en', models.CharField(blank=True, max_length=255)),
                ('description_uz', models.TextField()),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='persons', to='students.personcategory')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
