# Generated by Django 5.1.4 on 2026-04-21 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (En)')),
                ('content_uz', models.TextField(verbose_name='Matn (Uz)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('content_en', models.TextField(blank=True, verbose_name='Matn (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Talaba ma'lumoti",
                'verbose_name_plural': "Talaba ma'lumotlari",
                'db_table': 'students_student_info',
                'ordering': ['order'],
            },
        ),
    ]
