# Generated by Django 5.1.4 on 2026-04-21 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_student_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfoCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (En)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Ma'lumot kategoriyasi",
                'verbose_name_plural': "Ma'lumot kategoriyalari",
                'db_table': 'students_info_category',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='students.studentinfocategory', verbose_name='Kategoriya'),
        ),
    ]
