# Generated by Django 5.1.4 on 2026-04-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_add_student_info_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfocategory',
            options={'ordering': ['order'], 'verbose_name': 'Bakalavriat kategoriyasi', 'verbose_name_plural': 'Bakalavriat kategoriyalari'},
        ),
    ]
