# Generated by Django 5.1.4 on 2026-04-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_person_unified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personcategory',
            options={'ordering': ['order'], 'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='persons/%Y/%m/', verbose_name='Asosiy rasm'),
        ),
    ]
