# Generated by Django 5.1.4 on 2026-04-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentinfocategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='persons/%Y/%m/', verbose_name='Asosiy rasm'),
        ),
    ]
