# Generated by Django 5.1.4 on 2026-04-21 13:40

import domains.students.models.olimpiya_chempion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_make_image_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlimpiyaChempion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('full_name', models.CharField(blank=True, max_length=300, verbose_name="To'liq ismi")),
                ('image', models.ImageField(blank=True, null=True, upload_to=domains.students.models.olimpiya_chempion.olimpiya_image_upload, verbose_name='Rasm')),
                ('yonalish', models.CharField(blank=True, max_length=300, verbose_name="Yo'nalish (sport turi)")),
                ('guruh', models.CharField(blank=True, max_length=200, verbose_name='Guruh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Olimpiya chempioni',
                'verbose_name_plural': 'Olimpiya chempionlari',
                'db_table': 'students_olimpiya_chempion',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
