# Generated by Django 5.1.4 on 2026-04-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_olimpiya_chempion'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='students.personcategory', verbose_name='Ota kategoriya'),
        ),
        migrations.AddField(
            model_name='studentinfocategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='students.studentinfocategory', verbose_name='Ota kategoriya'),
        ),
    ]
