# Generated by Django 5.1.4 on 2026-04-23 13:19

import domains.students.models.olimpiya_chempion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_add_parent_to_person_and_studentinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olimpiyachempion',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=domains.students.models.olimpiya_chempion.olimpiya_image_upload, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='persons/%Y/%m/', verbose_name='Asosiy rasm'),
        ),
        migrations.AlterField(
            model_name='personimage',
            name='image',
            field=models.FileField(upload_to='persons/gallery/%Y/%m/', verbose_name='Rasm'),
        ),
    ]
