# Generated by Django 5.2.1 on 2026-04-25 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_olimpiyachempion_image_alter_person_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagistrGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('specialty_code', models.CharField(max_length=20, verbose_name='Mutaxassislik kodi')),
                ('specialty_name_uz', models.CharField(max_length=500, verbose_name='Mutaxassislik nomi (Uz)')),
                ('specialty_name_ru', models.CharField(blank=True, max_length=500, verbose_name='Mutaxassislik nomi (Ru)')),
                ('specialty_name_en', models.CharField(blank=True, max_length=500, verbose_name='Mutaxassislik nomi (En)')),
                ('education_lang', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Rus')], default='uz', max_length=5, verbose_name="Ta'lim tili")),
                ('year', models.CharField(help_text='Masalan: 2025-2026', max_length=20, verbose_name="O'quv yili")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Magistratura guruhi',
                'verbose_name_plural': 'Magistratura guruhlari',
                'db_table': 'students_magistr_group',
                'ordering': ['year', 'order', 'specialty_code'],
            },
        ),
        migrations.CreateModel(
            name='MagistrStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('student_name', models.CharField(max_length=300, verbose_name='Talabaning F.I.Sh.')),
                ('dissertation_topic_uz', models.TextField(verbose_name='Dissertatsiya mavzusi (Uz)')),
                ('dissertation_topic_ru', models.TextField(blank=True, verbose_name='Dissertatsiya mavzusi (Ru)')),
                ('dissertation_topic_en', models.TextField(blank=True, verbose_name='Dissertatsiya mavzusi (En)')),
                ('supervisor_name', models.CharField(max_length=300, verbose_name='Ilmiy rahbar F.I.Sh.')),
                ('supervisor_info_uz', models.CharField(blank=True, help_text='Masalan: p.f.d (DsC), dotsent', max_length=300, verbose_name='Ilmiy daraja va unvon (Uz)')),
                ('supervisor_info_ru', models.CharField(blank=True, max_length=300, verbose_name='Ilmiy daraja va unvon (Ru)')),
                ('supervisor_info_en', models.CharField(blank=True, max_length=300, verbose_name='Ilmiy daraja va unvon (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib (№)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.magistrgroup', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Magistratura talabasi',
                'verbose_name_plural': 'Magistratura talabalari',
                'db_table': 'students_magistr_student',
                'ordering': ['group', 'order'],
            },
        ),
    ]
