# Generated by Django 5.2.1 on 2026-04-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_seed_all_magistr_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Faks'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon'),
        ),
    ]
