# Generated by Django 5.2.1 on 2026-04-27 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_phone_fax_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stipendiya',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('status_uz', models.CharField(max_length=200, verbose_name='Status (Uz)')),
                ('status_ru', models.CharField(blank=True, max_length=200, verbose_name='Status (Ru)')),
                ('status_en', models.CharField(blank=True, max_length=200, verbose_name='Status (En)')),
                ('amount', models.PositiveIntegerField(verbose_name="Oylik miqdori (so'm)")),
                ('note_uz', models.CharField(blank=True, max_length=50, verbose_name='Izoh (Uz)')),
                ('note_ru', models.CharField(blank=True, max_length=50, verbose_name='Izoh (Ru)')),
                ('note_en', models.CharField(blank=True, max_length=50, verbose_name='Izoh (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Stipendiya',
                'verbose_name_plural': 'Stipendiyalar',
                'db_table': 'students_stipendiya',
                'ordering': ['order'],
            },
        ),
    ]
