# Generated by Django 5.2.1 on 2026-04-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_magistr_talaba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magistrtalaba',
            name='education_form_uz',
            field=models.CharField(blank=True, help_text='Kunduzgi / Sirtqi / Masofaviy', max_length=100, verbose_name="Ta'lim shakli (Uz)"),
        ),
        migrations.AlterField(
            model_name='magistrtalaba',
            name='year',
            field=models.CharField(blank=True, help_text='2024-2025', max_length=20, verbose_name="O'quv yili"),
        ),
    ]
