# Generated by Django 5.2.1 on 2026-05-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_magistrtalaba_education_form_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magistrtalaba',
            name='bio_en',
            field=models.TextField(blank=True, verbose_name='Bio/Tavsif (En)'),
        ),
        migrations.AddField(
            model_name='magistrtalaba',
            name='bio_ru',
            field=models.TextField(blank=True, verbose_name='Bio/Tavsif (Ru)'),
        ),
        migrations.AddField(
            model_name='magistrtalaba',
            name='bio_uz',
            field=models.TextField(blank=True, verbose_name='Bio/Tavsif (Uz)'),
        ),
        migrations.AddField(
            model_name='magistrtalaba',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='magistr_talabalar/%Y/%m/', verbose_name='Rasm'),
        ),
    ]
