# Generated by Django 5.2.1 on 2026-05-07 07:42

from django.db import migrations, models


def copy_old_to_uz(apps, schema_editor):
    Person = apps.get_model('students', 'Person')
    for p in Person.objects.all().only('id', 'address', 'reception', 'address_uz', 'reception_uz'):
        changed = False
        if p.address and not p.address_uz:
            p.address_uz = p.address
            changed = True
        if p.reception and not p.reception_uz:
            p.reception_uz = p.reception
            changed = True
        if changed:
            p.save(update_fields=['address_uz', 'reception_uz'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_add_image_bio_to_magistr_talaba'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Manzil (En)'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Manzil (Ru)'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Manzil (Uz)'),
        ),
        migrations.AddField(
            model_name='person',
            name='reception_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qabul vaqti (En)'),
        ),
        migrations.AddField(
            model_name='person',
            name='reception_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qabul vaqti (Ru)'),
        ),
        migrations.AddField(
            model_name='person',
            name='reception_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qabul vaqti (Uz)'),
        ),
        migrations.RunPython(copy_old_to_uz, noop_reverse),
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='reception',
        ),
    ]
