# Generated by Django 5.2.1 on 2026-05-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_olimpiya_chempion_multilang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olimpiyachempion',
            options={'ordering': ['order', 'full_name_uz'], 'verbose_name': 'Olimpiya chempioni', 'verbose_name_plural': 'Olimpiya chempionlari'},
        ),
    ]
