# Generated by Django 5.2.1 on 2026-05-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_seed_person_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magistrtalaba',
            options={'ordering': ['year', 'order', 'full_name_uz'], 'verbose_name': 'Magistratura talabasi (yangi)', 'verbose_name_plural': 'Magistratura talabalari (yangi)'},
        ),
    ]
