# Generated by Django 5.1.4 on 2026-03-31 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenderAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif (En)')),
                ('date', models.DateTimeField(verbose_name='Sana')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chiqarilsinmi?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
            ],
            options={
                'verbose_name': "Tender / E'lon",
                'verbose_name_plural': "Tenderlar va e'lonlar",
                'db_table': 'tenders_announcement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TenderImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to='tenders/%Y/%m/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tenders.tenderannouncement', verbose_name='Tender')),
            ],
            options={
                'db_table': 'tenders_image',
                'ordering': ['order'],
            },
        ),
    ]
