# Generated by Django 5.1.4 on 2026-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_add_likes_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderimage',
            name='image',
            field=models.FileField(upload_to='tenders/%Y/%m/', verbose_name='Rasm'),
        ),
    ]
