# Generated by Django 5.2.1 on 2026-05-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_alter_tenderimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderannouncement',
            name='announcement_type',
            field=models.CharField(choices=[('tender', 'Tender'), ('tanlov', "Tanlov (e'lon)")], default='tender', max_length=20, verbose_name='Turi'),
        ),
    ]
