# Generated by Django 5.2.1 on 2026-05-01 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qabul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QabulNavbar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title_uz', models.CharField(max_length=255, verbose_name='Nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Nomi (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Qabul navbar',
                'verbose_name_plural': 'Qabul navbar kategoriyalari',
                'db_table': 'qabul_navbar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QabulNavbarItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('slug', models.SlugField(max_length=150)),
                ('title_uz', models.CharField(max_length=255, verbose_name='Nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Nomi (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='qabul.qabulnavbar')),
            ],
            options={
                'verbose_name': 'Navbar item',
                'verbose_name_plural': 'Navbar itemlar',
                'db_table': 'qabul_navbar_item',
                'ordering': ['order'],
                'unique_together': {('navbar', 'slug')},
            },
        ),
    ]
