# Generated by Django 5.2.1 on 2026-05-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qabul', '0002_qabulnavbar_qabulnavbaritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='qabulnavbar',
            name='page_url',
            field=models.CharField(blank=True, help_text='Masalan: /qabul/bakalavr', max_length=500, verbose_name='Sahifa URL'),
        ),
        migrations.AddField(
            model_name='qabulnavbaritem',
            name='page_url',
            field=models.CharField(blank=True, help_text='Masalan: /qabul/bakalavr/ariza', max_length=500, verbose_name='Sahifa URL'),
        ),
    ]
