# Generated by Django 5.1.4 on 2026-04-10 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Nomi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (En)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Taglar',
                'db_table': 'common_tag',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('object_id', models.UUIDField()),
                ('image', models.ImageField(upload_to='content_images/%Y/%m/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Kontent rasmi',
                'verbose_name_plural': 'Kontent rasmlari',
                'db_table': 'common_content_image',
                'ordering': ['order'],
            },
        ),
    ]
