# Generated by Django 5.1.4 on 2026-03-24 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to='content/%Y/%m/', verbose_name='Asosiy rasm')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (En)')),
                ('text_uz', models.TextField(verbose_name="To'liq matn (Uz)")),
                ('text_ru', models.TextField(blank=True, verbose_name="To'liq matn (Ru)")),
                ('text_en', models.TextField(blank=True, verbose_name="To'liq matn (En)")),
                ('description_uz', models.TextField(blank=True, verbose_name='Qisqa tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Qisqa tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Qisqa tavsif (En)')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name="SEO Kalit so'zlar")),
                ('date', models.DateField(verbose_name='Sana')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Saytga chiqarilsinmi?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('location_uz', models.CharField(max_length=300, verbose_name='Manzil (Uz)')),
                ('location_ru', models.CharField(blank=True, max_length=300, verbose_name='Manzil (Ru)')),
                ('location_en', models.CharField(blank=True, max_length=300, verbose_name='Manzil (En)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Kutilayotgan tadbirlar',
                'db_table': 'news_event',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to='content/%Y/%m/', verbose_name='Asosiy rasm')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (En)')),
                ('text_uz', models.TextField(verbose_name="To'liq matn (Uz)")),
                ('text_ru', models.TextField(blank=True, verbose_name="To'liq matn (Ru)")),
                ('text_en', models.TextField(blank=True, verbose_name="To'liq matn (En)")),
                ('description_uz', models.TextField(blank=True, verbose_name='Qisqa tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Qisqa tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Qisqa tavsif (En)')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name="SEO Kalit so'zlar")),
                ('date', models.DateField(verbose_name='Sana')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Saytga chiqarilsinmi?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Manba (Link yoki nom)')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': "So'nggi yangiliklar",
                'db_table': 'news_news',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to='content/%Y/%m/', verbose_name='Asosiy rasm')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (En)')),
                ('text_uz', models.TextField(verbose_name="To'liq matn (Uz)")),
                ('text_ru', models.TextField(blank=True, verbose_name="To'liq matn (Ru)")),
                ('text_en', models.TextField(blank=True, verbose_name="To'liq matn (En)")),
                ('description_uz', models.TextField(blank=True, verbose_name='Qisqa tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Qisqa tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Qisqa tavsif (En)')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name="SEO Kalit so'zlar")),
                ('date', models.DateField(verbose_name='Sana')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Saytga chiqarilsinmi?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
                'db_table': 'news_blog',
            },
        ),
    ]
