# Generated by Django 5.1.4 on 2026-04-01 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to='content/%Y/%m/', verbose_name='Asosiy rasm')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(verbose_name='Batafsil (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Batafsil (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Batafsil (En)')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name="SEO Kalit so'zlar")),
                ('date', models.DateTimeField(verbose_name='Sana')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Saytga chiqarilsinmi?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('location_uz', models.CharField(max_length=300, verbose_name='Manzil (Uz)')),
                ('location_ru', models.CharField(blank=True, max_length=300, verbose_name='Manzil (Ru)')),
                ('location_en', models.CharField(blank=True, max_length=300, verbose_name='Manzil (En)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Kutilayotgan tadbirlar',
                'db_table': 'news_event',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to='content/%Y/%m/', verbose_name='Asosiy rasm')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(verbose_name='Batafsil (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Batafsil (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Batafsil (En)')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name="SEO Kalit so'zlar")),
                ('date', models.DateTimeField(verbose_name='Sana')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Saytga chiqarilsinmi?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Manba')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': "So'nggi yangiliklar",
                'db_table': 'news_news',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to='content/%Y/%m/', verbose_name='Asosiy rasm')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(verbose_name='Batafsil (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Batafsil (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Batafsil (En)')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name="SEO Kalit so'zlar")),
                ('date', models.DateTimeField(verbose_name='Sana')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Saytga chiqarilsinmi?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Bloglar',
                'db_table': 'news_blog',
            },
        ),
        migrations.CreateModel(
            name='InformationContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('content_type', models.CharField(choices=[('rector', 'Rektor tadbirlari va nutqlari'), ('briefing', 'Brifinglar'), ('contest', 'Tanlovlar'), ('press', 'Matbuot xizmati'), ('photo', 'Fotogalereya'), ('video', 'Videogalereya')], max_length=20, verbose_name='Tur')),
                ('title_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif (En)')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Sana')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Tashqi havola')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chiqarilsinmi?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('navbar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_items', to='pages.navbarsubitem', verbose_name='Navbar sahifasi')),
            ],
            options={
                'verbose_name': 'Axborot xizmati kontenti',
                'verbose_name_plural': 'Axborot xizmati kontentlari',
                'db_table': 'news_information_content',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Briefing',
            fields=[
            ],
            options={
                'verbose_name': 'Brifing',
                'verbose_name_plural': 'Brifinglar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
            ],
            options={
                'verbose_name': 'Tanlov',
                'verbose_name_plural': 'Tanlovlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
            ],
            options={
                'verbose_name': 'Fotogalereya',
                'verbose_name_plural': 'Fotogalereya',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
        migrations.CreateModel(
            name='PressService',
            fields=[
            ],
            options={
                'verbose_name': 'Matbuot xizmati',
                'verbose_name_plural': 'Matbuot xizmati',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
        migrations.CreateModel(
            name='RectorActivity',
            fields=[
            ],
            options={
                'verbose_name': 'Rektor tadbirlari va nutqlari',
                'verbose_name_plural': 'Rektor tadbirlari va nutqlari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
            ],
            options={
                'verbose_name': 'Videogalereya',
                'verbose_name_plural': 'Videogalereya',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
        migrations.CreateModel(
            name='InformationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to='information/%Y/%m/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.informationcontent', verbose_name='Kontent')),
            ],
            options={
                'db_table': 'news_information_image',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='informationcontent',
            index=models.Index(fields=['content_type', 'is_published'], name='news_inform_content_f79348_idx'),
        ),
        migrations.AddIndex(
            model_name='informationcontent',
            index=models.Index(fields=['navbar_item', 'content_type'], name='news_inform_navbar__053605_idx'),
        ),
    ]
