# Generated by Django 5.1.4 on 2026-04-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newscategory_article_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Batafsil (Uz)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/%Y/%m/', verbose_name='Asosiy rasm'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sarlavha (Uz)'),
        ),
    ]
