# Generated by Django 5.1.4 on 2026-04-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Tadbir', 'verbose_name_plural': 'Tadbirlar (Event)'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar (News)'},
        ),
    ]
