# Generated by Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_make_article_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.PositiveIntegerField(default=0, verbose_name='Komment soni'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Like soni'),
        ),
        migrations.AddField(
            model_name='informationcontent',
            name='comments',
            field=models.PositiveIntegerField(default=0, verbose_name='Komment soni'),
        ),
        migrations.AddField(
            model_name='informationcontent',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Like soni'),
        ),
    ]

