# Generated by Django 5.1.4 on 2026-03-30 05:15

from django.db import migrations, models


def copy_text_to_description(apps, schema_editor):
    for model_name in ['News', 'Event', 'Blog']:
        model = apps.get_model('news', model_name)
        for obj in model.objects.all().iterator():
            updated_fields = []

            if getattr(obj, 'text_uz', None) and not getattr(obj, 'description_uz', None):
                obj.description_uz = obj.text_uz
                updated_fields.append('description_uz')

            if getattr(obj, 'text_ru', None) and not getattr(obj, 'description_ru', None):
                obj.description_ru = obj.text_ru
                updated_fields.append('description_ru')

            if getattr(obj, 'text_en', None) and not getattr(obj, 'description_en', None):
                obj.description_en = obj.text_en
                updated_fields.append('description_en')

            if updated_fields:
                obj.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_convert_date_to_datetime'),
    ]

    operations = [
        migrations.RunPython(copy_text_to_description, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='blog',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='text_uz',
        ),
        migrations.RemoveField(
            model_name='event',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='event',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='event',
            name='text_uz',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='text_uz',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_en',
            field=models.TextField(blank=True, verbose_name="To'liq matn (En)"),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name="To'liq matn (Ru)"),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_uz',
            field=models.TextField(verbose_name="To'liq matn (Uz)"),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True, verbose_name="To'liq matn (En)"),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name="To'liq matn (Ru)"),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_uz',
            field=models.TextField(verbose_name="To'liq matn (Uz)"),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, verbose_name="To'liq matn (En)"),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name="To'liq matn (Ru)"),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_uz',
            field=models.TextField(verbose_name="To'liq matn (Uz)"),
        ),
    ]
