# Generated by Django 5.1.4 on 2026-03-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_blog_text_en_remove_blog_text_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Batafsil (En)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Batafsil (Ru)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_uz',
            field=models.TextField(verbose_name='Batafsil (Uz)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Batafsil (En)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Batafsil (Ru)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_uz',
            field=models.TextField(verbose_name='Batafsil (Uz)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Batafsil (En)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Batafsil (Ru)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description_uz',
            field=models.TextField(verbose_name='Batafsil (Uz)'),
        ),
    ]
