# Generated by Django 5.1.4 on 2026-04-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_tavsif_null_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.newscategory', verbose_name='Ota kategoriya'),
        ),
    ]
