# Generated by Django 5.1.4 on 2026-03-31 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_blog_description_en_alter_blog_description_ru_and_more'),
        ('pages', '0008_contentblock_linkblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Manba'),
        ),
        migrations.CreateModel(
            name='InformationContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('content_type', models.CharField(choices=[('rector', 'Rektor tadbirlari va nutqlari'), ('briefing', 'Brifinglar'), ('contest', 'Tanlovlar'), ('press', 'Matbuot xizmati'), ('photo', 'Fotogalereya'), ('video', 'Videogalereya')], max_length=20, verbose_name='Tur')),
                ('title_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif (En)')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Sana')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Tashqi havola')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chiqarilsinmi?')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('navbar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_items', to='pages.navbarsubitem', verbose_name='Navbar sahifasi')),
            ],
            options={
                'verbose_name': 'Axborot xizmati kontenti',
                'verbose_name_plural': 'Axborot xizmati kontentlari',
                'db_table': 'news_information_content',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to='information/%Y/%m/', verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.informationcontent', verbose_name='Kontent')),
            ],
            options={
                'db_table': 'news_information_image',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='informationcontent',
            index=models.Index(fields=['content_type', 'is_published'], name='news_inform_content_f79348_idx'),
        ),
        migrations.AddIndex(
            model_name='informationcontent',
            index=models.Index(fields=['navbar_item', 'content_type'], name='news_inform_navbar__053605_idx'),
        ),
    ]
