# Generated by Django 5.1.4 on 2026-03-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_source_informationcontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefing',
            fields=[
            ],
            options={
                'verbose_name': 'Brifing',
                'verbose_name_plural': 'Brifinglar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
            ],
            options={
                'verbose_name': 'Tanlov',
                'verbose_name_plural': 'Tanlovlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
            ],
            options={
                'verbose_name': 'Fotogalereya',
                'verbose_name_plural': 'Fotogalereya',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
        migrations.CreateModel(
            name='PressService',
            fields=[
            ],
            options={
                'verbose_name': 'Matbuot xizmati',
                'verbose_name_plural': 'Matbuot xizmati',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
        migrations.CreateModel(
            name='RectorActivity',
            fields=[
            ],
            options={
                'verbose_name': 'Rektor tadbirlari va nutqlari',
                'verbose_name_plural': 'Rektor tadbirlari va nutqlari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
            ],
            options={
                'verbose_name': 'Videogalereya',
                'verbose_name_plural': 'Videogalereya',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
    ]
