# Generated by Django 5.1.4 on 2026-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_add_parent_to_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='content/%Y/%m/', verbose_name='Asosiy rasm'),
        ),
        migrations.AlterField(
            model_name='informationimage',
            name='image',
            field=models.FileField(upload_to='information/%Y/%m/', verbose_name='Rasm'),
        ),
    ]
