# Generated by Django 5.2.1 on 2026-04-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_image_alter_informationimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='event_status',
            field=models.CharField(blank=True, choices=[('upcoming', 'Kutilayotgan'), ('completed', 'Tugallangan')], db_index=True, default='upcoming', max_length=10, verbose_name='Tadbir holati'),
        ),
    ]
