# Generated by Django 5.2.1 on 2026-04-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_article_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korrupsiya',
            fields=[
            ],
            options={
                'verbose_name': 'Korrupsiyaga qarshi kurash',
                'verbose_name_plural': 'Korrupsiyaga qarshi kurash',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.article',),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('news', 'Yangilik'), ('event', 'Tadbir'), ('blog', 'Blog'), ('korrupsiya', 'Korrupsiyaga qarshi kurash')], db_index=True, max_length=10, verbose_name='Tur'),
        ),
    ]
