# Generated by Django 5.2.1 on 2026-04-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_add_korrupsiya_article_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elon',
            fields=[
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.informationcontent',),
        ),
        migrations.AlterField(
            model_name='informationcontent',
            name='content_type',
            field=models.CharField(choices=[('rector', 'Rektor tadbirlari va nutqlari'), ('briefing', 'Brifinglar'), ('contest', 'Tanlovlar'), ('elon', "E'lonlar"), ('press', 'Matbuot xizmati'), ('photo', 'Fotogalereya'), ('video', 'Videogalereya')], max_length=20, verbose_name='Tur'),
        ),
    ]
