# Generated by Django 5.2.1 on 2026-05-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_elon_alter_informationcontent_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_en',
            field=models.FileField(blank=True, null=True, upload_to='content/%Y/%m/', verbose_name='Asosiy rasm (En)'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_ru',
            field=models.FileField(blank=True, null=True, upload_to='content/%Y/%m/', verbose_name='Asosiy rasm (Ru)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='content/%Y/%m/', verbose_name='Asosiy rasm (Uz)'),
        ),
    ]
