# Generated by Django 5.2.1 on 2026-05-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_article_image_en_article_image_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationimage',
            name='image',
        ),
        migrations.AddField(
            model_name='informationimage',
            name='image_en',
            field=models.FileField(blank=True, null=True, upload_to='information/%Y/%m/', verbose_name='Rasm (EN)'),
        ),
        migrations.AddField(
            model_name='informationimage',
            name='image_ru',
            field=models.FileField(blank=True, null=True, upload_to='information/%Y/%m/', verbose_name='Rasm (RU)'),
        ),
        migrations.AddField(
            model_name='informationimage',
            name='image_uz',
            field=models.FileField(blank=True, null=True, upload_to='information/%Y/%m/', verbose_name='Rasm (UZ)'),
        ),
    ]
