# Generated by Django 5.1.4 on 2026-04-13 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('specialty_code', models.CharField(max_length=20, verbose_name='Mutaxassislik kodi')),
                ('specialty_name_uz', models.CharField(max_length=300, verbose_name='Mutaxassislik nomi (Uz)')),
                ('specialty_name_ru', models.CharField(blank=True, max_length=300, verbose_name='Mutaxassislik nomi (Ru)')),
                ('specialty_name_en', models.CharField(blank=True, max_length=300, verbose_name='Mutaxassislik nomi (En)')),
                ('education_type', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistratura')], default='bachelor', max_length=20, verbose_name="Ta'lim darajasi")),
                ('education_form', models.CharField(choices=[('daytime', 'Kunduzgi'), ('evening', 'Kechki'), ('distance', 'Sirtqi')], default='daytime', max_length=20, verbose_name="Ta'lim shakli")),
                ('price', models.PositiveIntegerField(verbose_name="To'lov miqdori (so'm)")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Kontrakt narxi',
                'verbose_name_plural': "To'lov-kontrakt narxlari",
                'db_table': 'activities_contract_price',
                'ordering': ['education_type', 'education_form', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name', models.CharField(max_length=200, verbose_name='Rusumi (modeli)')),
                ('vehicle_type_uz', models.CharField(max_length=200, verbose_name='Transport vositasi turi (Uz)')),
                ('vehicle_type_ru', models.CharField(blank=True, max_length=200, verbose_name='Transport vositasi turi (Ru)')),
                ('vehicle_type_en', models.CharField(blank=True, max_length=200, verbose_name='Transport vositasi turi (En)')),
                ('manufactured_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ishlab chiqarilgan yili')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Benzin'), ('diesel', 'Dizel'), ('gas', 'Gaz'), ('electric', 'Elektr'), ('hybrid', 'Gibrid')], default='petrol', max_length=20, verbose_name="Yoqilg'i turi")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Xizmat avtomobili',
                'verbose_name_plural': 'Xizmat avtomototransport vositalari',
                'db_table': 'activities_service_vehicle',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
