# Generated by Django 5.1.4 on 2026-04-21 13:07

import domains.activities.models.ilmiy_faoliyat
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlmiyFaoliyat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (En)')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='Muallif(lar)')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yil')),
                ('category', models.CharField(choices=[('article', 'Maqola'), ('monograph', 'Monografiya'), ('manual', "O'quv qo'llanma"), ('report', 'Hisobot'), ('patent', 'Patent'), ('conference', 'Konferensiya'), ('other', 'Boshqa')], default='other', max_length=30, verbose_name='Turi')),
                ('image', models.ImageField(blank=True, null=True, upload_to=domains.activities.models.ilmiy_faoliyat.ilmiy_image_upload, verbose_name='Muqova rasmi')),
                ('file', models.FileField(blank=True, help_text="PDF, DOCX, DOC, PPTX formatlari qo'llab-quvvatlanadi", null=True, upload_to=domains.activities.models.ilmiy_faoliyat.ilmiy_file_upload, verbose_name='Fayl (PDF / DOC)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Ilmiy faoliyat',
                'verbose_name_plural': 'Ilmiy faoliyat',
                'db_table': 'activities_ilmiy_faoliyat',
                'ordering': ['-year', 'order'],
            },
        ),
    ]
