# Generated by Django 5.1.4 on 2026-04-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_ilmiyfaoliyatcategory_ilmiyfaoliyat_category_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ilmiyfaoliyat',
            old_name='category',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='ilmiyfaoliyat',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='ilmiyfaoliyat',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='ilmiyfaoliyat',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='ilmiyfaoliyat',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='ilmiyfaoliyat',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='ilmiyfaoliyat',
            name='title_uz',
        ),
    ]
