# Generated by Django 5.1.4 on 2026-04-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_rename_category_ilmiyfaoliyat_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilmiyfaoliyat',
            options={'ordering': ['order'], 'verbose_name': 'Ilmiy faoliyat', 'verbose_name_plural': 'Ilmiy faoliyat'},
        ),
        migrations.RenameField(
            model_name='ilmiyfaoliyat',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='ilmiyfaoliyat',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ilmiyfaoliyat',
            name='type',
        ),
        migrations.RemoveField(
            model_name='ilmiyfaoliyat',
            name='year',
        ),
    ]
