# Generated by Django 5.1.4 on 2026-04-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_ilmiyfaoliyat_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ilmiyfaoliyat',
            options={'ordering': ['order'], 'verbose_name': "O'quv faoliyat", 'verbose_name_plural': "O'quv faoliyat"},
        ),
        migrations.AlterModelOptions(
            name='ilmiyfaoliyatcategory',
            options={'ordering': ['order', 'title_uz'], 'verbose_name': "O'quv faoliyat kategoriyasi", 'verbose_name_plural': "O'quv faoliyat kategoriyalari"},
        ),
    ]
