# Generated by Django 5.1.4 on 2026-04-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_ilmiyfaoliyat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmiyfaoliyatcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='activities.ilmiyfaoliyatcategory', verbose_name='Ota kategoriya'),
        ),
    ]
