# Generated by Django 5.1.4 on 2026-04-23 13:19

import domains.activities.models.ilmiy_faoliyat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_add_parent_to_ilmiy_faoliyat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilmiyfaoliyat',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=domains.activities.models.ilmiy_faoliyat.ilmiy_image_upload, verbose_name='Muqova rasmi'),
        ),
    ]
