# Generated by Django 5.1.4 on 2026-04-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_alter_ilmiyfaoliyat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmiyfaoliyat',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (En)'),
        ),
        migrations.AddField(
            model_name='ilmiyfaoliyat',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (Ru)'),
        ),
        migrations.AddField(
            model_name='ilmiyfaoliyat',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (Uz)'),
        ),
        migrations.AddField(
            model_name='ilmiyfaoliyatcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (En)'),
        ),
        migrations.AddField(
            model_name='ilmiyfaoliyatcategory',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (Ru)'),
        ),
        migrations.AddField(
            model_name='ilmiyfaoliyatcategory',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (Uz)'),
        ),
    ]
