# Generated by Django 5.2.1 on 2026-04-26 08:04

import domains.activities.models.ilmiy_faoliyat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_add_description_to_ilmiy_faoliyat_and_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilmiyfaoliyat',
            name='file',
            field=models.FileField(blank=True, help_text="PDF, DOCX, DOC, PPTX formatlari qo'llab-quvvatlanadi", max_length=500, null=True, upload_to=domains.activities.models.ilmiy_faoliyat.ilmiy_file_upload, verbose_name='Fayl (PDF / DOC)'),
        ),
    ]
