# Generated by Django 5.2.1 on 2026-04-28 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_add_icon_to_ilmiy_faoliyat_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (En)')),
                ('value', models.PositiveIntegerField(verbose_name='Qiymat')),
                ('suffix', models.CharField(blank=True, default='+', max_length=10, verbose_name="Qo'shimcha belgi")),
                ('color', models.CharField(blank=True, default='', max_length=30, verbose_name='Rang kodi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Sport statistika',
                'verbose_name_plural': 'Sport statistikalar',
                'db_table': 'activities_sport_stat',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SportTadbir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Nomi (En)')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif (En)')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Sana')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Sport tadbiri',
                'verbose_name_plural': 'Sport tadbirlari',
                'db_table': 'activities_sport_tadbir',
                'ordering': ['order', 'event_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SportYonalish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (En)')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif (En)')),
                ('icon', models.CharField(blank=True, default='', max_length=20, verbose_name='Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': "Sport yo'nalishi",
                'verbose_name_plural': "Sport yo'nalishlari",
                'db_table': 'activities_sport_yonalish',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
