# Generated by Django 5.2.1 on 2026-04-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_sportstat_sporttadbir_sportyonalish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportstat',
            options={'ordering': ['order'], 'verbose_name': 'Sport statistika', 'verbose_name_plural': 'Sport statistikalar'},
        ),
        migrations.AlterModelOptions(
            name='sporttadbir',
            options={'ordering': ['order', 'event_date'], 'verbose_name': 'Sport tadbiri', 'verbose_name_plural': 'Sport tadbirlari'},
        ),
        migrations.AlterModelOptions(
            name='sportyonalish',
            options={'ordering': ['order'], 'verbose_name': "Sport yo'nalishi", 'verbose_name_plural': "Sport yo'nalishlari"},
        ),
        migrations.AddField(
            model_name='sporttadbir',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Joyi (En)'),
        ),
        migrations.AddField(
            model_name='sporttadbir',
            name='location_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Joyi (Ru)'),
        ),
        migrations.AddField(
            model_name='sporttadbir',
            name='location_uz',
            field=models.CharField(blank=True, max_length=200, verbose_name='Joyi (Uz)'),
        ),
        migrations.AlterField(
            model_name='sportstat',
            name='suffix',
            field=models.CharField(blank=True, default='+', max_length=10, verbose_name="Qo'shimcha belgi (+, K+)"),
        ),
        migrations.AlterField(
            model_name='sportstat',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tavsif (En)'),
        ),
        migrations.AlterField(
            model_name='sportstat',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tavsif (Ru)'),
        ),
        migrations.AlterField(
            model_name='sportstat',
            name='title_uz',
            field=models.CharField(max_length=200, verbose_name='Tavsif (Uz)'),
        ),
        migrations.AlterField(
            model_name='sportstat',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Qiymat (son)'),
        ),
        migrations.AlterField(
            model_name='sporttadbir',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (En)'),
        ),
        migrations.AlterField(
            model_name='sporttadbir',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (Ru)'),
        ),
        migrations.AlterField(
            model_name='sporttadbir',
            name='title_uz',
            field=models.CharField(max_length=300, verbose_name='Sarlavha (Uz)'),
        ),
        migrations.AlterField(
            model_name='sportyonalish',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif (En)'),
        ),
        migrations.AlterField(
            model_name='sportyonalish',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif (Ru)'),
        ),
        migrations.AlterField(
            model_name='sportyonalish',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Qisqa tavsif (Uz)'),
        ),
        migrations.AlterField(
            model_name='sportyonalish',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Emoji yoki icon'),
        ),
    ]
