# Generated by Django 5.2.1 on 2026-04-29 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_add_location_to_sport_tadbir'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxborotVazifa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Vazifa (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Vazifa (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Vazifa (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Axborot vazifasi',
                'verbose_name_plural': 'Axborot vazifalari',
                'db_table': 'activities_axborot_vazifa',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AxborotXodim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('full_name_uz', models.CharField(max_length=200, verbose_name="To'liq ismi (Uz)")),
                ('full_name_ru', models.CharField(blank=True, max_length=200, verbose_name="To'liq ismi (Ru)")),
                ('full_name_en', models.CharField(blank=True, max_length=200, verbose_name="To'liq ismi (En)")),
                ('position_uz', models.CharField(max_length=300, verbose_name='Lavozimi (Uz)')),
                ('position_ru', models.CharField(blank=True, max_length=300, verbose_name='Lavozimi (Ru)')),
                ('position_en', models.CharField(blank=True, max_length=300, verbose_name='Lavozimi (En)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='axborot/xodimlar/', verbose_name='Surat')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Axborot xizmati xodimi',
                'verbose_name_plural': 'Axborot xizmati xodimlari',
                'db_table': 'activities_axborot_xodim',
                'ordering': ['order'],
            },
        ),
    ]
