# Generated by Django 5.2.1 on 2026-05-07 08:06

import django.db.models.deletion
import domains.activities.models.ilmiy_yonalish
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_add_axborot_xizmati'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlmiyYonalish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Nomi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Nomi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Nomi (En)')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': "Ilmiy yo'nalish",
                'verbose_name_plural': "Ilmiy yo'nalishlar",
                'db_table': 'activities_ilmiy_yonalish',
                'ordering': ['order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='IlmiyYonalishItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Nomi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Nomi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Nomi (En)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (En)')),
                ('photo', models.FileField(blank=True, null=True, upload_to=domains.activities.models.ilmiy_yonalish.ilmiy_yonalish_image_upload, verbose_name='Rasm')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='activities.ilmiyyonalish', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': "Ilmiy yo'nalish elementi",
                'verbose_name_plural': "Ilmiy yo'nalish elementlari",
                'db_table': 'activities_ilmiy_yonalish_item',
                'ordering': ['order', 'name_uz'],
            },
        ),
    ]
