# Generated by Django 5.2.1 on 2026-05-11 10:54

import domains.activities.models.ilmiy_kontent
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_ilmiyyonalish_ilmiyyonalishitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlmiyJurnal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name_uz', models.CharField(max_length=500, verbose_name='Nomi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=500, verbose_name='Nomi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=500, verbose_name='Nomi (En)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (En)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=domains.activities.models.ilmiy_kontent.ilmiy_kontent_image_upload, verbose_name='Rasm')),
                ('link', models.URLField(blank=True, verbose_name='Jurnal sayti (URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Ilmiy jurnal',
                'verbose_name_plural': 'Ilmiy jurnallar',
                'db_table': 'activities_ilmiy_jurnal',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IlmiyKengashSeminar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('tipi', models.CharField(choices=[('kengash', 'Ilmiy kengash'), ('seminar', 'Ilmiy seminar')], default='kengash', max_length=10, verbose_name='Tipi')),
                ('shifr', models.CharField(help_text="Masalan: DSc.28/2025.27.12.Ped.01.01 (pedagogika fanlari bo'yicha)", max_length=200, verbose_name='Shifr va nomi')),
                ('buyruq_sanasi', models.CharField(blank=True, help_text='Masalan: 27.12.2025 №1599', max_length=100, verbose_name='Buyruq sanasi va raqami')),
                ('ixtisoslik_shifri', models.CharField(blank=True, max_length=200, verbose_name='Ixtisoslik shifri')),
                ('ixtisoslik_nomi_uz', models.TextField(blank=True, verbose_name='Ixtisoslik nomi (Uz)')),
                ('ixtisoslik_nomi_ru', models.TextField(blank=True, verbose_name='Ixtisoslik nomi (Ru)')),
                ('ixtisoslik_nomi_en', models.TextField(blank=True, verbose_name='Ixtisoslik nomi (En)')),
                ('rais_uz', models.CharField(blank=True, max_length=300, verbose_name='Rais F.I.SH (Uz)')),
                ('rais_ru', models.CharField(blank=True, max_length=300, verbose_name='Rais F.I.SH (Ru)')),
                ('rais_en', models.CharField(blank=True, max_length=300, verbose_name='Rais F.I.SH (En)')),
                ('rais_lavozim_uz', models.CharField(blank=True, max_length=300, verbose_name='Rais ilmiy darajasi (Uz)')),
                ('rais_lavozim_ru', models.CharField(blank=True, max_length=300, verbose_name='Rais ilmiy darajasi (Ru)')),
                ('rais_lavozim_en', models.CharField(blank=True, max_length=300, verbose_name='Rais ilmiy darajasi (En)')),
                ('kotib_uz', models.CharField(blank=True, max_length=300, verbose_name='Kotib F.I.SH (Uz)')),
                ('kotib_ru', models.CharField(blank=True, max_length=300, verbose_name='Kotib F.I.SH (Ru)')),
                ('kotib_en', models.CharField(blank=True, max_length=300, verbose_name='Kotib F.I.SH (En)')),
                ('kotib_lavozim_uz', models.CharField(blank=True, max_length=300, verbose_name='Kotib ilmiy darajasi (Uz)')),
                ('kotib_lavozim_ru', models.CharField(blank=True, max_length=300, verbose_name='Kotib ilmiy darajasi (Ru)')),
                ('kotib_lavozim_en', models.CharField(blank=True, max_length=300, verbose_name='Kotib ilmiy darajasi (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Ilmiy kengash/seminar',
                'verbose_name_plural': 'Ilmiy kengash va seminarlar',
                'db_table': 'activities_ilmiy_kengash_seminar',
                'ordering': ['tipi', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IlmiyKontentSahifa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('kategoriya', models.CharField(choices=[('jurnallar', 'Ilmiy jurnallar'), ('kengash', 'Ilmiy kengash va seminar'), ('loyihalar', 'Ilmiy loyihalar'), ('maktablar', 'Ilmiy maktablar')], max_length=20, unique=True, verbose_name='Kategoriya')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (En)')),
                ('intro_uz', models.TextField(blank=True, verbose_name='Intro matn (Uz)')),
                ('intro_ru', models.TextField(blank=True, verbose_name='Intro matn (Ru)')),
                ('intro_en', models.TextField(blank=True, verbose_name='Intro matn (En)')),
            ],
            options={
                'verbose_name': 'Ilmiy kontent sahifasi',
                'verbose_name_plural': 'Ilmiy kontent sahifalari',
                'db_table': 'activities_ilmiy_kontent_sahifa',
            },
        ),
        migrations.CreateModel(
            name='IlmiyLoyiha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('raqami_uz', models.CharField(help_text="Masalan: Bajarilishi 2027-2028 - yillarga mo'ljallangan Amaliy loyiha", max_length=300, verbose_name='Loyiha raqami va muddati (Uz)')),
                ('raqami_ru', models.CharField(blank=True, max_length=300, verbose_name='Loyiha raqami va muddati (Ru)')),
                ('raqami_en', models.CharField(blank=True, max_length=300, verbose_name='Loyiha raqami va muddati (En)')),
                ('mavzusi_uz', models.TextField(verbose_name='Loyiha mavzusi (Uz)')),
                ('mavzusi_ru', models.TextField(blank=True, verbose_name='Loyiha mavzusi (Ru)')),
                ('mavzusi_en', models.TextField(blank=True, verbose_name='Loyiha mavzusi (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Ilmiy loyiha',
                'verbose_name_plural': 'Ilmiy loyihalar',
                'db_table': 'activities_ilmiy_loyiha',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IlmiyMaktab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('nomi_uz', models.CharField(max_length=300, verbose_name='Maktab nomi (Uz)')),
                ('nomi_ru', models.CharField(blank=True, max_length=300, verbose_name='Maktab nomi (Ru)')),
                ('nomi_en', models.CharField(blank=True, max_length=300, verbose_name='Maktab nomi (En)')),
                ('asoschi_uz', models.CharField(max_length=300, verbose_name='Asoschi (Uz)')),
                ('asoschi_ru', models.CharField(blank=True, max_length=300, verbose_name='Asoschi (Ru)')),
                ('asoschi_en', models.CharField(blank=True, max_length=300, verbose_name='Asoschi (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Ilmiy maktab',
                'verbose_name_plural': 'Ilmiy maktablar',
                'db_table': 'activities_ilmiy_maktab',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
