# Generated by Django 5.2.1 on 2026-05-16 05:05

import domains.activities.models.ilmiy_faoliyat
import domains.activities.models.ilmiy_kontent
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_sport_natija_kalendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilmiyfaoliyat',
            name='image_en',
            field=models.FileField(blank=True, null=True, upload_to=domains.activities.models.ilmiy_faoliyat.ilmiy_image_upload, verbose_name='Muqova rasmi (En)'),
        ),
        migrations.AddField(
            model_name='ilmiyfaoliyat',
            name='image_ru',
            field=models.FileField(blank=True, null=True, upload_to=domains.activities.models.ilmiy_faoliyat.ilmiy_image_upload, verbose_name='Muqova rasmi (Ru)'),
        ),
        migrations.AddField(
            model_name='ilmiyjurnal',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=domains.activities.models.ilmiy_kontent.ilmiy_kontent_image_upload, verbose_name='Rasm (En)'),
        ),
        migrations.AddField(
            model_name='ilmiyjurnal',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=domains.activities.models.ilmiy_kontent.ilmiy_kontent_image_upload, verbose_name='Rasm (Ru)'),
        ),
        migrations.AlterField(
            model_name='ilmiyfaoliyat',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=domains.activities.models.ilmiy_faoliyat.ilmiy_image_upload, verbose_name='Muqova rasmi (Uz)'),
        ),
        migrations.AlterField(
            model_name='ilmiyjurnal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=domains.activities.models.ilmiy_kontent.ilmiy_kontent_image_upload, verbose_name='Rasm (Uz)'),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='jahon_chempionati',
            field=models.PositiveIntegerField(default=0, verbose_name='Jahon chempionati'),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='jahon_kubogi',
            field=models.PositiveIntegerField(default=0, verbose_name='Jahon kubogi'),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='jahon_seriyasi',
            field=models.PositiveIntegerField(default=0, verbose_name='Jahon seriyasi'),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='osiyo_chempionati',
            field=models.PositiveIntegerField(default=0, verbose_name='Osiyo chempionati'),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='osiyo_kubogi',
            field=models.PositiveIntegerField(default=0, verbose_name='Osiyo kubogi'),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='osiyo_oyinlari',
            field=models.PositiveIntegerField(default=0, verbose_name="Osiyo o'yinlari"),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='ozb_chempionati',
            field=models.PositiveIntegerField(default=0, verbose_name="O'zbekiston chempionati"),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='ozb_kubogi',
            field=models.PositiveIntegerField(default=0, verbose_name="O'zbekiston kubogi"),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='prezident_olimpiyada',
            field=models.PositiveIntegerField(default=0, verbose_name='Prezident olimpiyadasi'),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='xalqaro_turnir',
            field=models.PositiveIntegerField(default=0, verbose_name='Xalqaro turnir'),
        ),
        migrations.AlterField(
            model_name='sportkalendar',
            name='yoshlar_olimpiya',
            field=models.PositiveIntegerField(default=0, verbose_name="Yoshlar olimpiya o'yinlari"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='jahon_chempionati_1',
            field=models.PositiveIntegerField(default=0, verbose_name="Jahon chempionati — 1-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='jahon_chempionati_2',
            field=models.PositiveIntegerField(default=0, verbose_name="Jahon chempionati — 2-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='jahon_chempionati_3',
            field=models.PositiveIntegerField(default=0, verbose_name="Jahon chempionati — 3-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='mdh_1',
            field=models.PositiveIntegerField(default=0, verbose_name="MDH o'yinlari — 1-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='mdh_2',
            field=models.PositiveIntegerField(default=0, verbose_name="MDH o'yinlari — 2-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='mdh_3',
            field=models.PositiveIntegerField(default=0, verbose_name="MDH o'yinlari — 3-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='osiyo_chempionati_1',
            field=models.PositiveIntegerField(default=0, verbose_name="Osiyo chempionati — 1-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='osiyo_chempionati_2',
            field=models.PositiveIntegerField(default=0, verbose_name="Osiyo chempionati — 2-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='osiyo_chempionati_3',
            field=models.PositiveIntegerField(default=0, verbose_name="Osiyo chempionati — 3-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='osiyo_kubogi_1',
            field=models.PositiveIntegerField(default=0, verbose_name="Osiyo kubogi — 1-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='osiyo_kubogi_2',
            field=models.PositiveIntegerField(default=0, verbose_name="Osiyo kubogi — 2-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='osiyo_kubogi_3',
            field=models.PositiveIntegerField(default=0, verbose_name="Osiyo kubogi — 3-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='osiyo_yoshlar_1',
            field=models.PositiveIntegerField(default=0, verbose_name="Osiyo yoshlar — 1-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='osiyo_yoshlar_2',
            field=models.PositiveIntegerField(default=0, verbose_name="Osiyo yoshlar — 2-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='osiyo_yoshlar_3',
            field=models.PositiveIntegerField(default=0, verbose_name="Osiyo yoshlar — 3-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='para_osiyo_1',
            field=models.PositiveIntegerField(default=0, verbose_name="Para osiyo — 1-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='para_osiyo_2',
            field=models.PositiveIntegerField(default=0, verbose_name="Para osiyo — 2-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='para_osiyo_3',
            field=models.PositiveIntegerField(default=0, verbose_name="Para osiyo — 3-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='xalqaro_turnir_1',
            field=models.PositiveIntegerField(default=0, verbose_name="Xalqaro turnir — 1-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='xalqaro_turnir_2',
            field=models.PositiveIntegerField(default=0, verbose_name="Xalqaro turnir — 2-o'rin"),
        ),
        migrations.AlterField(
            model_name='sportnatija',
            name='xalqaro_turnir_3',
            field=models.PositiveIntegerField(default=0, verbose_name="Xalqaro turnir — 3-o'rin"),
        ),
    ]
