# Generated by Django 5.2.1 on 2026-05-18 11:54

import domains.activities.models.ilmiy_kontent
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_ilmiyfaoliyat_image_en_ilmiyfaoliyat_image_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlmiyAnjuman',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (En)')),
                ('date', models.DateField(verbose_name='Sana')),
                ('location_uz', models.CharField(blank=True, max_length=300, verbose_name='Manzil (Uz)')),
                ('location_ru', models.CharField(blank=True, max_length=300, verbose_name='Manzil (Ru)')),
                ('location_en', models.CharField(blank=True, max_length=300, verbose_name='Manzil (En)')),
                ('turi', models.CharField(choices=[('republic', 'Respublika konferensiyasi'), ('international', 'Xalqaro konferensiya'), ('seminar', 'Ilmiy seminar'), ('roundtable', 'Davra suhbati'), ('webinar', 'Vebinar')], default='republic', max_length=20, verbose_name='Turi')),
                ('status', models.CharField(choices=[('upcoming', 'Kutilmoqda'), ('ongoing', 'Davom etmoqda'), ('past', "O'tkazildi")], default='upcoming', max_length=10, verbose_name='Holati')),
                ('image', models.ImageField(blank=True, null=True, upload_to=domains.activities.models.ilmiy_kontent.anjuman_image_upload, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Ilmiy anjuman',
                'verbose_name_plural': 'Ilmiy anjumanlar',
                'db_table': 'activities_ilmiy_anjuman',
                'ordering': ['-date', 'order'],
            },
        ),
    ]
