# Generated by Django 5.2.1 on 2026-04-27 12:33

import django.db.models.deletion
import domains.infra.models.sport_majmua
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportMajmua',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name_uz', models.CharField(max_length=300, verbose_name='Nomi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=300, verbose_name='Nomi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='Nomi (En)')),
                ('location_uz', models.CharField(blank=True, max_length=300, verbose_name='Joylashuvi (Uz)')),
                ('location_ru', models.CharField(blank=True, max_length=300, verbose_name='Joylashuvi (Ru)')),
                ('location_en', models.CharField(blank=True, max_length=300, verbose_name='Joylashuvi (En)')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Sport majmuasi',
                'verbose_name_plural': 'Sport majmualari',
                'db_table': 'infra_sport_majmua',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SportMajmuaImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.FileField(upload_to=domains.infra.models.sport_majmua.majmua_image_upload, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('majmua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='infra.sportmajmua', verbose_name='Majmua')),
            ],
            options={
                'verbose_name': 'Majmua rasmi',
                'verbose_name_plural': 'Majmua rasmlari',
                'db_table': 'infra_sport_majmua_image',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SportMajmuaSportTuri',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Sport turi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Sport turi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Sport turi (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('majmua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_types', to='infra.sportmajmua', verbose_name='Majmua')),
            ],
            options={
                'verbose_name': 'Sport turi',
                'verbose_name_plural': 'Sport turlari',
                'db_table': 'infra_sport_majmua_sport_turi',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SportMajmuaStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('label_uz', models.CharField(max_length=300, verbose_name='Maydon nomi (Uz)')),
                ('label_ru', models.CharField(blank=True, max_length=300, verbose_name='Maydon nomi (Ru)')),
                ('label_en', models.CharField(blank=True, max_length=300, verbose_name='Maydon nomi (En)')),
                ('value_uz', models.CharField(max_length=500, verbose_name='Qiymati (Uz)')),
                ('value_ru', models.CharField(blank=True, max_length=500, verbose_name='Qiymati (Ru)')),
                ('value_en', models.CharField(blank=True, max_length=500, verbose_name='Qiymati (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('majmua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='infra.sportmajmua', verbose_name='Majmua')),
            ],
            options={
                'verbose_name': "Texnik ko'rsatkich",
                'verbose_name_plural': "Texnik ko'rsatkichlar",
                'db_table': 'infra_sport_majmua_stat',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SportMajmuaTadbir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('level', models.CharField(choices=[('xalqaro', 'Xalqaro'), ('maxaliy', 'Mahalliy')], max_length=10, verbose_name='Daraja')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Tadbir nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Tadbir nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Tadbir nomi (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('majmua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='infra.sportmajmua', verbose_name='Majmua')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'db_table': 'infra_sport_majmua_tadbir',
                'ordering': ['level', 'order'],
            },
        ),
    ]
