# Generated by Django 5.2.1 on 2026-04-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_sharoit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharoit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='sharoit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
    ]
