# Generated by Django 5.2.1 on 2026-05-14 12:19

import django.db.models.deletion
import domains.infra.models.olimpiya
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_alter_sharoit_created_at_alter_sharoit_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlimpiyaShaharchasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('intro_uz', models.TextField(blank=True, verbose_name='Kirish matni (Uz)')),
                ('intro_ru', models.TextField(blank=True, verbose_name='Kirish matni (Ru)')),
                ('intro_en', models.TextField(blank=True, verbose_name='Kirish matni (En)')),
                ('gallery_title_uz', models.CharField(blank=True, default='Fotogaleriya', max_length=300, verbose_name='Galereya sarlavhasi (Uz)')),
                ('gallery_title_ru', models.CharField(blank=True, default='Фотогалерея', max_length=300, verbose_name='Galereya sarlavhasi (Ru)')),
                ('gallery_title_en', models.CharField(blank=True, default='Photo gallery', max_length=300, verbose_name='Galereya sarlavhasi (En)')),
            ],
            options={
                'verbose_name': 'Olimpiya shaharchasi',
                'verbose_name_plural': 'Olimpiya shaharchasi',
                'db_table': 'infra_olimpiya_shaharchasi',
            },
        ),
        migrations.CreateModel(
            name='OlimpiyaGalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.FileField(upload_to=domains.infra.models.olimpiya.olimpiya_gallery_upload, verbose_name='Rasm')),
                ('caption_uz', models.CharField(blank=True, max_length=300, verbose_name='Izoh (Uz)')),
                ('caption_ru', models.CharField(blank=True, max_length=300, verbose_name='Izoh (Ru)')),
                ('caption_en', models.CharField(blank=True, max_length=300, verbose_name='Izoh (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('shaharchasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='infra.olimpiyashaharchasi', verbose_name='Shaharchasi')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'db_table': 'infra_olimpiya_gallery_image',
                'ordering': ['order'],
            },
        ),
    ]
