# Generated by Django 5.2.1 on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra", "0004_olimpiya_shaharchasi"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportmajmua",
            name="category",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Kategoriya"),
        ),
    ]

