# Generated by Django 5.2.1 on 2026-05-16

from django.db import migrations, models


def copy_category_to_i18n(apps, schema_editor):
    SportMajmua = apps.get_model("infra", "SportMajmua")
    for obj in SportMajmua.objects.all():
        old_value = getattr(obj, "category", "") or ""
        obj.category_uz = old_value
        obj.category_ru = old_value
        obj.category_en = old_value
        obj.save(update_fields=["category_uz", "category_ru", "category_en"])


class Migration(migrations.Migration):

    dependencies = [
        ("infra", "0005_sportmajmua_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportmajmua",
            name="category_en",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Kategoriya (En)"),
        ),
        migrations.AddField(
            model_name="sportmajmua",
            name="category_ru",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Kategoriya (Ru)"),
        ),
        migrations.AddField(
            model_name="sportmajmua",
            name="category_uz",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Kategoriya (Uz)"),
        ),
        migrations.RunPython(copy_category_to_i18n, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="sportmajmua",
            name="category",
        ),
    ]

