# Generated by Django 5.2.1 on 2026-05-16

from django.db import migrations


def fill_i18n_defaults(apps, schema_editor):
    SportMajmua = apps.get_model("infra", "SportMajmua")
    SportMajmuaStat = apps.get_model("infra", "SportMajmuaStat")
    SportMajmuaSportTuri = apps.get_model("infra", "SportMajmuaSportTuri")
    SportMajmuaTadbir = apps.get_model("infra", "SportMajmuaTadbir")

    for obj in SportMajmua.objects.all():
        changed = False
        if not (obj.name_ru or "").strip():
            obj.name_ru = obj.name_uz or ""
            changed = True
        if not (obj.name_en or "").strip():
            obj.name_en = obj.name_uz or ""
            changed = True
        if not (obj.location_ru or "").strip():
            obj.location_ru = obj.location_uz or ""
            changed = True
        if not (obj.location_en or "").strip():
            obj.location_en = obj.location_uz or ""
            changed = True
        if not (obj.category_ru or "").strip():
            obj.category_ru = obj.category_uz or ""
            changed = True
        if not (obj.category_en or "").strip():
            obj.category_en = obj.category_uz or ""
            changed = True
        if changed:
            obj.save(
                update_fields=[
                    "name_ru",
                    "name_en",
                    "location_ru",
                    "location_en",
                    "category_ru",
                    "category_en",
                ]
            )

    for obj in SportMajmuaStat.objects.all():
        changed = False
        if not (obj.label_ru or "").strip():
            obj.label_ru = obj.label_uz or ""
            changed = True
        if not (obj.label_en or "").strip():
            obj.label_en = obj.label_uz or ""
            changed = True
        if not (obj.value_ru or "").strip():
            obj.value_ru = obj.value_uz or ""
            changed = True
        if not (obj.value_en or "").strip():
            obj.value_en = obj.value_uz or ""
            changed = True
        if changed:
            obj.save(update_fields=["label_ru", "label_en", "value_ru", "value_en"])

    for obj in SportMajmuaSportTuri.objects.all():
        changed = False
        if not (obj.name_ru or "").strip():
            obj.name_ru = obj.name_uz or ""
            changed = True
        if not (obj.name_en or "").strip():
            obj.name_en = obj.name_uz or ""
            changed = True
        if changed:
            obj.save(update_fields=["name_ru", "name_en"])

    for obj in SportMajmuaTadbir.objects.all():
        changed = False
        if not (obj.title_ru or "").strip():
            obj.title_ru = obj.title_uz or ""
            changed = True
        if not (obj.title_en or "").strip():
            obj.title_en = obj.title_uz or ""
            changed = True
        if changed:
            obj.save(update_fields=["title_ru", "title_en"])


class Migration(migrations.Migration):

    dependencies = [
        ("infra", "0006_sportmajmua_category_i18n"),
    ]

    operations = [
        migrations.RunPython(fill_i18n_defaults, migrations.RunPython.noop),
    ]

