# Generated by Django 5.2.1 on 2026-05-16

from django.db import migrations


def clear_cloned_translations(apps, schema_editor):
    SportMajmua = apps.get_model("infra", "SportMajmua")
    SportMajmuaStat = apps.get_model("infra", "SportMajmuaStat")
    SportMajmuaSportTuri = apps.get_model("infra", "SportMajmuaSportTuri")
    SportMajmuaTadbir = apps.get_model("infra", "SportMajmuaTadbir")

    for obj in SportMajmua.objects.all():
        changed = False
        if (obj.name_ru or "").strip() == (obj.name_uz or "").strip() and (obj.name_uz or "").strip():
            obj.name_ru = ""
            changed = True
        if (obj.name_en or "").strip() == (obj.name_uz or "").strip() and (obj.name_uz or "").strip():
            obj.name_en = ""
            changed = True
        if (obj.location_ru or "").strip() == (obj.location_uz or "").strip() and (obj.location_uz or "").strip():
            obj.location_ru = ""
            changed = True
        if (obj.location_en or "").strip() == (obj.location_uz or "").strip() and (obj.location_uz or "").strip():
            obj.location_en = ""
            changed = True
        if (obj.category_ru or "").strip() == (obj.category_uz or "").strip() and (obj.category_uz or "").strip():
            obj.category_ru = ""
            changed = True
        if (obj.category_en or "").strip() == (obj.category_uz or "").strip() and (obj.category_uz or "").strip():
            obj.category_en = ""
            changed = True
        if changed:
            obj.save(
                update_fields=[
                    "name_ru",
                    "name_en",
                    "location_ru",
                    "location_en",
                    "category_ru",
                    "category_en",
                ]
            )

    for obj in SportMajmuaStat.objects.all():
        changed = False
        if (obj.label_ru or "").strip() == (obj.label_uz or "").strip() and (obj.label_uz or "").strip():
            obj.label_ru = ""
            changed = True
        if (obj.label_en or "").strip() == (obj.label_uz or "").strip() and (obj.label_uz or "").strip():
            obj.label_en = ""
            changed = True
        if (obj.value_ru or "").strip() == (obj.value_uz or "").strip() and (obj.value_uz or "").strip():
            obj.value_ru = ""
            changed = True
        if (obj.value_en or "").strip() == (obj.value_uz or "").strip() and (obj.value_uz or "").strip():
            obj.value_en = ""
            changed = True
        if changed:
            obj.save(update_fields=["label_ru", "label_en", "value_ru", "value_en"])

    for obj in SportMajmuaSportTuri.objects.all():
        changed = False
        if (obj.name_ru or "").strip() == (obj.name_uz or "").strip() and (obj.name_uz or "").strip():
            obj.name_ru = ""
            changed = True
        if (obj.name_en or "").strip() == (obj.name_uz or "").strip() and (obj.name_uz or "").strip():
            obj.name_en = ""
            changed = True
        if changed:
            obj.save(update_fields=["name_ru", "name_en"])

    for obj in SportMajmuaTadbir.objects.all():
        changed = False
        if (obj.title_ru or "").strip() == (obj.title_uz or "").strip() and (obj.title_uz or "").strip():
            obj.title_ru = ""
            changed = True
        if (obj.title_en or "").strip() == (obj.title_uz or "").strip() and (obj.title_uz or "").strip():
            obj.title_en = ""
            changed = True
        if changed:
            obj.save(update_fields=["title_ru", "title_en"])


class Migration(migrations.Migration):

    dependencies = [
        ("infra", "0007_fill_sport_majmua_i18n_defaults"),
    ]

    operations = [
        migrations.RunPython(clear_cloned_translations, migrations.RunPython.noop),
    ]

