# Generated by Django 5.1.4 on 2026-04-02 04:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('role', models.CharField(choices=[('rector', 'Rektor'), ('prorector', 'Prorektor'), ('dean', 'Dekan'), ('dept_head', 'Kafedra mudiri'), ('council_member', "Kengash a'zosi"), ('staff', 'Xodim')], max_length=20, verbose_name='Lavozim turi')),
                ('is_head', models.BooleanField(default=False, verbose_name='Rahbar xodimmi?')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Lavozim nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Lavozim nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Lavozim nomi (En)')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('position_uz', models.CharField(blank=True, max_length=255, verbose_name='Ilmiy daraja / unvon (Uz)')),
                ('position_ru', models.CharField(blank=True, max_length=255, verbose_name='Ilmiy daraja / unvon (Ru)')),
                ('position_en', models.CharField(blank=True, max_length=255, verbose_name='Ilmiy daraja / unvon (En)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/%Y/%m/', verbose_name='Rasm')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('reception', models.CharField(blank=True, max_length=100, verbose_name='Qabul vaqti')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Batafsil (Uz)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Batafsil (Ru)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Batafsil (En)')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('fax', models.CharField(blank=True, max_length=25, verbose_name='Faks')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'db_table': 'academic_staff',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('content_uz', models.TextField(blank=True, verbose_name='Matn (Uz)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('content_en', models.TextField(blank=True, verbose_name='Matn (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Xodim tabi',
                'verbose_name_plural': 'Xodim tablari',
                'db_table': 'academic_staff_content',
                'ordering': ['order'],
            },
        ),
    ]
