# Generated by Django 5.1.4 on 2026-03-30 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Nomi (En)')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('unit_type', models.CharField(choices=[('council', 'Universitet kengashi'), ('supervisory', 'Kuzatuv kengashi'), ('rector', 'Rektor'), ('prorector', 'Prorektor'), ('faculty', 'Fakultet'), ('department', 'Kafedra'), ('center', 'Markaz'), ('institute', 'Institut'), ('public_org', 'Jamoat tashkiloti'), ('division', "Bo'lim")], max_length=20, verbose_name='Bo‘lim turi')),
                ('content_uz', models.TextField(blank=True, verbose_name='To‘liq matn (Uz)')),
                ('content_ru', models.TextField(blank=True, verbose_name='To‘liq matn (Ru)')),
                ('content_en', models.TextField(blank=True, verbose_name='To‘liq matn (En)')),
                ('has_own_page', models.BooleanField(default=False, verbose_name='Alohida sahifasi bormi?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy ajratilgan blokmi?')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='academic.organizationunit', verbose_name='Yuqori bo‘lim')),
            ],
            options={
                'verbose_name': "Tashkiliy bo'linma",
                'verbose_name_plural': "Tashkiliy bo'linmalar",
                'db_table': 'academic_organization_unit',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('role', models.CharField(choices=[('rector', 'Rektor'), ('prorector', 'Prorektor'), ('dean', 'Dekan'), ('dept_head', 'Kafedra mudiri'), ('council_member', "Kengash a'zosi"), ('staff', 'Xodim')], max_length=20, verbose_name='Lavozim turi')),
                ('is_head', models.BooleanField(default=False, verbose_name='Rahbar xodimmi?')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Lavozim nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Lavozim nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Lavozim nomi (En)')),
                ('full_name', models.CharField(max_length=255, verbose_name='To‘liq ism')),
                ('position_uz', models.CharField(blank=True, max_length=255, verbose_name='Ilmiy daraja / unvon (Uz)')),
                ('position_ru', models.CharField(blank=True, max_length=255, verbose_name='Ilmiy daraja / unvon (Ru)')),
                ('position_en', models.CharField(blank=True, max_length=255, verbose_name='Ilmiy daraja / unvon (En)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/%Y/%m/', verbose_name='Rasm')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('reception_uz', models.CharField(blank=True, max_length=100, verbose_name='Qabul vaqti (Uz)')),
                ('reception_ru', models.CharField(blank=True, max_length=100, verbose_name='Qabul vaqti (Ru)')),
                ('reception_en', models.CharField(blank=True, max_length=100, verbose_name='Qabul vaqti (En)')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('fax', models.CharField(blank=True, max_length=25, verbose_name='Faks')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='academic.organizationunit', verbose_name='Bo‘lim')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'db_table': 'academic_staff',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['unit_type', 'is_active'], name='academic_or_unit_ty_8b084a_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['slug'], name='academic_or_slug_74023b_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['parent', 'order'], name='academic_or_parent__23f409_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['unit', 'order'], name='academic_st_unit_id_b33452_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['role', 'is_active'], name='academic_st_role_71b1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_head'], name='academic_st_is_head_1bff79_idx'),
        ),
    ]
