# Generated by Django 5.1.4 on 2026-04-10 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('label_uz', models.CharField(max_length=300, verbose_name='Yorliq (Uz)')),
                ('label_ru', models.CharField(blank=True, max_length=300, verbose_name='Yorliq (Ru)')),
                ('label_en', models.CharField(blank=True, max_length=300, verbose_name='Yorliq (En)')),
                ('value_uz', models.CharField(max_length=300, verbose_name='Qiymat (Uz)')),
                ('value_ru', models.CharField(blank=True, max_length=300, verbose_name='Qiymat (Ru)')),
                ('value_en', models.CharField(blank=True, max_length=300, verbose_name='Qiymat (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Akademiya raqamda',
                'verbose_name_plural': "Akademiya raqamlarda va Stipendiyalar bo'limi",
                'db_table': 'academic_academy_stat',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
