# Generated by Django 5.1.4 on 2026-03-30 06:01

from django.db import migrations, models


def copy_reception_from_uz(apps, schema_editor):
    Staff = apps.get_model('academic', 'Staff')
    for staff in Staff.objects.all().iterator():
        if getattr(staff, 'reception_uz', None):
            staff.reception = staff.reception_uz
            staff.save(update_fields=['reception'])


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil'),
        ),
        migrations.AddField(
            model_name='staff',
            name='reception',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qabul vaqti'),
        ),
        migrations.RunPython(copy_reception_from_uz, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='staff',
            name='reception_en',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='reception_ru',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='reception_uz',
        ),
    ]
