# Generated by Django 5.1.4 on 2026-04-02 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('common', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='navbar_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='pages.navbarsubitem', verbose_name='Navbar sahifasi'),
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='academic.staff', verbose_name='Xodim'),
        ),
        migrations.AddField(
            model_name='staffcontent',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_contents', to='common.tag', verbose_name='Tab nomi (Tag)'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['navbar_item', 'order'], name='academic_st_navbar__fe0da6_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['role', 'is_active'], name='academic_st_role_71b1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_head'], name='academic_st_is_head_1bff79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffcontent',
            unique_together={('staff', 'tag')},
        ),
    ]
