# Generated by Django 5.1.4 on 2026-04-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academystat',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Akademiya raqamda', 'verbose_name_plural': 'Akademiya raqamlarda'},
        ),
    ]
