# Generated by Django 5.1.4 on 2026-03-30 06:05

from django.db import migrations, models


def copy_description_to_uz(apps, schema_editor):
    Staff = apps.get_model('academic', 'Staff')
    for staff in Staff.objects.all().iterator():
        if getattr(staff, 'description', None):
            staff.description_uz = staff.description
            staff.save(update_fields=['description_uz'])


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_remove_staff_reception_en_remove_staff_reception_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil (En)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil (Ru)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil (Uz)'),
        ),
        migrations.RunPython(copy_description_to_uz, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='staff',
            name='description',
        ),
    ]
