# Generated by Django 5.2.1 on 2026-04-25 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_academydetailpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakultetKafedra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('type', models.CharField(choices=[('fakultet', 'Fakultet'), ('kafedra', 'Kafedra')], default='kafedra', max_length=20, verbose_name='Turi')),
                ('name_uz', models.CharField(max_length=300, verbose_name='Nomi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=300, verbose_name='Nomi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='Nomi (En)')),
                ('link', models.URLField(blank=True, verbose_name='Havola (URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Fakultet / Kafedra',
                'verbose_name_plural': 'Fakultetlar va kafedralar',
                'db_table': 'academic_fakultet_kafedra',
                'ordering': ['order', 'name_uz'],
            },
        ),
    ]
