# Generated by Django 5.1.4 on 2026-03-30 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_staff_description_staff_description_en_and_more'),
        ('pages', '0006_herovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationunit',
            name='navbar_item',
            field=models.OneToOneField(blank=True, help_text='Tanlansa, slug avtomatik navbar slug bilan bir xil bo‘ladi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_unit', to='pages.navbarsubitem', verbose_name='Bog‘langan navbar sahifasi'),
        ),
    ]
