# Generated by Django 5.2.1 on 2026-04-25 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    FakultetKafedra = apps.get_model('academic', 'FakultetKafedra')
    for obj in FakultetKafedra.objects.filter(slug=''):
        base = slugify(obj.name_uz) or uuid.uuid4().hex[:12]
        slug, counter = base, 1
        while FakultetKafedra.objects.filter(slug=slug).exclude(pk=obj.pk).exists():
            slug = f'{base}-{counter}'
            counter += 1
        obj.slug = slug
        obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_add_fakultet_kafedra'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakultetkafedra',
            name='bachelor_subjects_en',
            field=models.TextField(blank=True, verbose_name='Bakalavriat fanlari (En)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='bachelor_subjects_ru',
            field=models.TextField(blank=True, verbose_name='Bakalavriat fanlari (Ru)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='bachelor_subjects_uz',
            field=models.TextField(blank=True, help_text='Har birini yangi satrga yozing', verbose_name='Bakalavriat fanlari (Uz)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='decree_info',
            field=models.CharField(blank=True, max_length=300, verbose_name='Asos hujjat (farmon/qaror)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Tavsif (En)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (Ru)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name='Tavsif (Uz)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='email',
            field=models.CharField(blank=True, max_length=200, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='master_subjects_en',
            field=models.TextField(blank=True, verbose_name='Magistratura fanlari (En)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='master_subjects_ru',
            field=models.TextField(blank=True, verbose_name='Magistratura fanlari (Ru)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='master_subjects_uz',
            field=models.TextField(blank=True, help_text='Har birini yangi satrga yozing', verbose_name='Magistratura fanlari (Uz)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='Slug', default=''),
        ),
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fakultetkafedra',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='sport_types_en',
            field=models.TextField(blank=True, verbose_name='Sport turlari (En)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='sport_types_ru',
            field=models.TextField(blank=True, verbose_name='Sport turlari (Ru)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='sport_types_uz',
            field=models.TextField(blank=True, help_text='Har birini yangi satrga yozing', verbose_name='Sport turlari (Uz)'),
        ),
        migrations.AlterField(
            model_name='fakultetkafedra',
            name='link',
            field=models.URLField(blank=True, verbose_name='Tashqi havola (URL)'),
        ),
        migrations.CreateModel(
            name='KafedraPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (En)')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='Muallif(lar)')),
                ('pub_type', models.CharField(choices=[('monograf', 'Monografiya'), ('darslik', 'Darslik'), ('qollanma', "O'quv qo'llanma")], default='monograf', max_length=20, verbose_name='Turi')),
                ('cover', models.FileField(blank=True, null=True, upload_to='kafedra/publications/', verbose_name='Muqova rasmi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='academic.fakultetkafedra', verbose_name='Kafedra')),
            ],
            options={
                'verbose_name': 'Kafedra nashri',
                'verbose_name_plural': 'Kafedra nashrlari',
                'db_table': 'academic_kafedra_publication',
                'ordering': ['order', 'title_uz'],
            },
        ),
    ]
