# Generated by Django 5.1.4 on 2026-03-30 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_organizationunit_navbar_item'),
        ('pages', '0007_staff_navbar_item'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='staff',
            name='academic_st_unit_id_b33452_idx',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='unit',
        ),
        migrations.AddField(
            model_name='staff',
            name='navbar_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='pages.navbarsubitem', verbose_name='Navbar sahifasi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name="To'liq ism"),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['navbar_item', 'order'], name='academic_st_navbar__fe0da6_idx'),
        ),
    ]
