# Generated by Django 5.1.4 on 2026-03-31 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_delete_organizationunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('content_uz', models.TextField(blank=True, verbose_name='Matn (Uz)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('content_en', models.TextField(blank=True, verbose_name='Matn (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='academic.staff', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Xodim tabi',
                'verbose_name_plural': 'Xodim tablari',
                'db_table': 'academic_staff_content',
                'ordering': ['order'],
            },
        ),
    ]
