# Generated by Django 5.1.4 on 2026-03-31 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_staffcontent'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcontent',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_contents', to='common.tag', verbose_name='Tab nomi (Tag)'),
        ),
        migrations.AlterUniqueTogether(
            name='staffcontent',
            unique_together={('staff', 'tag')},
        ),
    ]
