# Generated by Django 5.1.4 on 2026-04-10 10:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_academy_stat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academystat',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Akademiya raqamda', 'verbose_name_plural': "Akademiya raqamlarda va Stipendiyalar bo'limi"},
        ),
        migrations.AlterField(
            model_name='academystat',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
