# Generated by Django 5.2.1 on 2026-04-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_update_ijtimoiy_tashkilotlar_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultetkafedra',
            name='type',
            field=models.CharField(choices=[('fakultet', 'Fakultet'), ('kafedra', 'Kafedra'), ('tashkilot', 'Tashkilot')], default='kafedra', max_length=20, verbose_name='Turi'),
        ),
    ]
