# Generated by Django 5.2.1 on 2026-04-28 06:59

import django.db.models.deletion
import domains.academic.models.kafedra_xodim
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_alter_fakultetkafedra_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafedraXodim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('full_name', models.CharField(max_length=300, verbose_name="To'liq ismi")),
                ('position_uz', models.CharField(max_length=300, verbose_name='Lavozimi (Uz)')),
                ('position_ru', models.CharField(blank=True, max_length=300, verbose_name='Lavozimi (Ru)')),
                ('position_en', models.CharField(blank=True, max_length=300, verbose_name='Lavozimi (En)')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='E-mail')),
                ('photo', models.FileField(blank=True, null=True, upload_to=domains.academic.models.kafedra_xodim.xodim_photo_upload, verbose_name='Surat')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xodimlar', to='academic.fakultetkafedra', verbose_name='Fakultet / Kafedra')),
            ],
            options={
                'verbose_name': 'Kafedra xodimi',
                'verbose_name_plural': 'Kafedra xodimlari',
                'db_table': 'academic_kafedra_xodim',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
