# Generated by Django 5.2.1 on 2026-04-28 07:09

import django.db.models.deletion
import domains.academic.models.kafedra_rasm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_add_kafedra_xodim'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafedraRasm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.FileField(upload_to=domains.academic.models.kafedra_rasm.kafedra_rasm_upload, verbose_name='Rasm')),
                ('caption_uz', models.CharField(blank=True, max_length=300, verbose_name='Izoh (Uz)')),
                ('caption_ru', models.CharField(blank=True, max_length=300, verbose_name='Izoh (Ru)')),
                ('caption_en', models.CharField(blank=True, max_length=300, verbose_name='Izoh (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='academic.fakultetkafedra', verbose_name='Fakultet / Kafedra')),
            ],
            options={
                'verbose_name': 'Kafedra rasmi',
                'verbose_name_plural': 'Kafedra rasmlari',
                'db_table': 'academic_kafedra_rasm',
                'ordering': ['order'],
            },
        ),
    ]
