# Generated by Django 5.2.1 on 2026-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_kafedra_xodim_use_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kafedraxodim',
            options={'ordering': ['order'], 'verbose_name': 'Kafedra xodimi', 'verbose_name_plural': 'Kafedra xodimlari'},
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='about_en',
            field=models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot (En)"),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='about_ru',
            field=models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot (Ru)"),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='about_uz',
            field=models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot (Uz)"),
        ),
    ]
