# Generated by Django 5.2.1 on 2026-04-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_add_about_to_fakultet'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakultetkafedra',
            name='dean_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dekan e-mail'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='dean_name_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dekan ismi (En)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='dean_name_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dekan ismi (Ru)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='dean_name_uz',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dekan ismi (Uz)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='dean_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dekan telefoni'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='dean_photo',
            field=models.ImageField(blank=True, null=True, upload_to='akademik/dekan/', verbose_name='Dekan rasmi'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='mudiri_degree_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mudiri ilmiy darajasi (En)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='mudiri_degree_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mudiri ilmiy darajasi (Ru)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='mudiri_degree_uz',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mudiri ilmiy darajasi (Uz)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='mudiri_email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mudiri e-mail'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='mudiri_name_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mudiri ismi (En)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='mudiri_name_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mudiri ismi (Ru)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='mudiri_name_uz',
            field=models.CharField(blank=True, max_length=300, verbose_name='Mudiri ismi (Uz)'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='mudiri_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mudiri telefoni'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='mudiri_photo',
            field=models.ImageField(blank=True, null=True, upload_to='akademik/mudiri/', verbose_name='Mudiri rasmi'),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='vice_dean_email',
            field=models.CharField(blank=True, max_length=200, verbose_name="O'rinbosar e-mail"),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='vice_dean_name_en',
            field=models.CharField(blank=True, max_length=300, verbose_name="O'rinbosar ismi (En)"),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='vice_dean_name_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name="O'rinbosar ismi (Ru)"),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='vice_dean_name_uz',
            field=models.CharField(blank=True, max_length=300, verbose_name="O'rinbosar ismi (Uz)"),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='vice_dean_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name="O'rinbosar telefoni"),
        ),
        migrations.AddField(
            model_name='fakultetkafedra',
            name='vice_dean_photo',
            field=models.ImageField(blank=True, null=True, upload_to='akademik/orbosar/', verbose_name="O'rinbosar rasmi"),
        ),
    ]
