# Generated by Django 5.2.1 on 2026-04-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_huzuridagi_tashkilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huzuridagitashkilot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='huzuridagitashkilot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
    ]
