# Generated by Django 5.2.1 on 2026-04-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_alter_huzuridagitashkilot_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='huzuridagitashkilot',
            name='about_en',
            field=models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot (En)"),
        ),
        migrations.AddField(
            model_name='huzuridagitashkilot',
            name='about_ru',
            field=models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot (Ru)"),
        ),
        migrations.AddField(
            model_name='huzuridagitashkilot',
            name='about_uz',
            field=models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumot (Uz)"),
        ),
        migrations.AddField(
            model_name='huzuridagitashkilot',
            name='org_type',
            field=models.CharField(choices=[('akademiya', 'Akademiya huzuridagi'), ('jamoat', 'Jamoat tashkiloti')], default='akademiya', max_length=20, verbose_name='Tashkilot turi'),
        ),
    ]
