# Generated by Django 5.2.1 on 2026-04-30 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_huzuridagi_tashkilot_org_type_about'),
        ('students', '0015_alter_magistrtalaba_education_form_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='huzuridagitashkilot',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jamoat_tashkilot_links', to='students.person', verbose_name='Rahbar (Person)'),
        ),
    ]
