# Generated by Django 5.2.1 on 2026-04-30 06:44

from django.db import migrations, models
from django.utils.text import slugify
import uuid


def fill_slugs(apps, schema_editor):
    HuzuridagiTashkilot = apps.get_model('academic', 'HuzuridagiTashkilot')
    for obj in HuzuridagiTashkilot.objects.all():
        base = slugify(obj.name_uz) or uuid.uuid4().hex[:12]
        slug, counter = base, 1
        while HuzuridagiTashkilot.objects.filter(slug=slug).exclude(pk=obj.pk).exists():
            slug = f'{base}-{counter}'
            counter += 1
        obj.slug = slug
        obj.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_huzuridagi_tashkilot_person_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='huzuridagitashkilot',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=False, verbose_name='Slug', default=''),
            preserve_default=False,
        ),
        migrations.RunPython(fill_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='huzuridagitashkilot',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
