# Generated by Django 5.2.1 on 2026-05-03 14:41

import domains.academic.models.tashkiliy_tuzilma
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_huzuridagi_tashkilot_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TashkiliyTuzilmaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('text_uz', models.TextField(verbose_name='Matn (Uz)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('text_en', models.TextField(blank=True, verbose_name='Matn (En)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=domains.academic.models.tashkiliy_tuzilma.tashkiliy_tuzilma_image_upload, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Tashkiliy tuzilma elementi',
                'verbose_name_plural': 'Tashkiliy tuzilma elementlari',
                'db_table': 'academic_tashkiliy_tuzilma_item',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
