# Generated by Django 5.2.1 on 2026-05-16 05:05

import domains.academic.models.huzuridagi_tashkilot
import domains.academic.models.tashkiliy_tuzilma
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_tashkiliytuzilmaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='huzuridagitashkilot',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=domains.academic.models.huzuridagi_tashkilot.tashkilot_image_upload, verbose_name='Rasm (En)'),
        ),
        migrations.AddField(
            model_name='huzuridagitashkilot',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=domains.academic.models.huzuridagi_tashkilot.tashkilot_image_upload, verbose_name='Rasm (Ru)'),
        ),
        migrations.AddField(
            model_name='tashkiliytuzilmaitem',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=domains.academic.models.tashkiliy_tuzilma.tashkiliy_tuzilma_image_upload, verbose_name='Rasm (En)'),
        ),
        migrations.AddField(
            model_name='tashkiliytuzilmaitem',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=domains.academic.models.tashkiliy_tuzilma.tashkiliy_tuzilma_image_upload, verbose_name='Rasm (Ru)'),
        ),
        migrations.AlterField(
            model_name='huzuridagitashkilot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=domains.academic.models.huzuridagi_tashkilot.tashkilot_image_upload, verbose_name='Rasm (Uz)'),
        ),
        migrations.AlterField(
            model_name='tashkiliytuzilmaitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=domains.academic.models.tashkiliy_tuzilma.tashkiliy_tuzilma_image_upload, verbose_name='Rasm (Uz)'),
        ),
    ]
