# Generated by Django 5.2.1 on 2026-05-18 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0025_huzuridagitashkilot_add_kengash_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huzuridagitashkilotrasm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        # PostgreSQL cannot cast bigint→uuid directly (USING "id"::uuid fails).
        # Instead: add a new uuid column, drop the old bigint pk, rename.
        migrations.RunSQL(
            sql="""
                ALTER TABLE "academic_huzuridagi_tashkilot_rasm"
                    ADD COLUMN "_new_id" uuid DEFAULT gen_random_uuid() NOT NULL;
                ALTER TABLE "academic_huzuridagi_tashkilot_rasm"
                    DROP CONSTRAINT "academic_huzuridagi_tashkilot_rasm_pkey";
                ALTER TABLE "academic_huzuridagi_tashkilot_rasm"
                    DROP COLUMN "id";
                ALTER TABLE "academic_huzuridagi_tashkilot_rasm"
                    RENAME COLUMN "_new_id" TO "id";
                ALTER TABLE "academic_huzuridagi_tashkilot_rasm"
                    ALTER COLUMN "id" DROP DEFAULT;
                ALTER TABLE "academic_huzuridagi_tashkilot_rasm"
                    ADD PRIMARY KEY ("id");
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterField(
                    model_name='huzuridagitashkilotrasm',
                    name='id',
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='huzuridagitashkilotrasm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
    ]
