# Generated by Django 5.2.1 on 2026-05-18 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0025_huzuridagitashkilot_add_kengash_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huzuridagitashkilotrasm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='huzuridagitashkilotrasm',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='huzuridagitashkilotrasm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
    ]
