# Generated by Django 5.2.1 on 2026-05-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0026_alter_huzuridagitashkilotrasm_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedraxodim',
            name='lavozim_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lavozim (En)'),
        ),
        migrations.AddField(
            model_name='kafedraxodim',
            name='lavozim_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lavozim (Ru)'),
        ),
        migrations.AddField(
            model_name='kafedraxodim',
            name='lavozim_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lavozim (Uz)'),
        ),
    ]
