"""
python manage.py seed_tuzilma           # yaratadi / yangilaydi
python manage.py seed_tuzilma --clear   # o'chirib qaytadan yozadi
"""
from django.core.management.base import BaseCommand
from domains.academic.models import FakultetKafedra

DATA = [

    # ── 1. KUZATUV KENGASHI ───────────────────────────────────────────────────
    {
        'slug':    'akademiya-kengashi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   101,
        'name_uz': "Akademiya kengashi",
        'name_ru': "Совет академии",
        'name_en': "Academy Council",
        'description_uz': "Akademiya kengashi oliy boshqaruv organi sifatida akademiyaning strategik rivojlanish yo'nalishlarini belgilaydi, ilmiy-ta'lim siyosatini shakllantiradi va muhim qarorlar qabul qiladi.",
        'description_ru': "Совет академии как высший орган управления определяет стратегические направления развития академии, формирует научно-образовательную политику и принимает важные решения.",
        'description_en': "The Academy Council as the supreme governing body determines the strategic development directions of the academy, forms scientific and educational policy, and makes important decisions.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'xalqaro-maslahatchi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   102,
        'name_uz': "Xalqaro maslahatchi",
        'name_ru': "Международный советник",
        'name_en': "International Adviser",
        'description_uz': "Xalqaro maslahatchi xorijiy hamkorlar va xalqaro tashkilotlar bilan aloqalarni mustahkamlash, akademiyaning global miqyosdagi obro'sini oshirish bo'yicha faoliyat yuritadi.",
        'description_ru': "Международный советник занимается укреплением связей с зарубежными партнёрами и международными организациями, повышением авторитета академии на мировом уровне.",
        'description_en': "The International Adviser works on strengthening ties with foreign partners and international organisations, enhancing the academy's global reputation.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'rektor',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   103,
        'name_uz': "Rektor",
        'name_ru': "Ректор",
        'name_en': "Rector",
        'description_uz': "Akademiya rektori muassasaning umumiy rahbari bo'lib, ta'lim, ilmiy va ma'muriy faoliyatni boshqaradi, akademiyani ichki va tashqi manfaatlar doirasida ifodalaydi.",
        'description_ru': "Ректор академии является общим руководителем учреждения, управляет образовательной, научной и административной деятельностью, представляет академию во внутренних и внешних интересах.",
        'description_en': "The Rector of the academy is the general head of the institution, managing educational, scientific and administrative activities, representing the academy in internal and external affairs.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'rektor-yordamchisi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   104,
        'name_uz': "Rektor yordamchisi",
        'name_ru': "Помощник ректора",
        'name_en': "Rector's Assistant",
        'description_uz': "Rektor yordamchisi kundalik ma'muriy ishlarni muvofiqlashtiradi, rektor topshiriqlarini bajaradi va tuzilmaviy bo'limlar faoliyatini nazorat qiladi.",
        'description_ru': "Помощник ректора координирует повседневную административную работу, выполняет поручения ректора и осуществляет контроль за деятельностью структурных подразделений.",
        'description_en': "The Rector's Assistant coordinates day-to-day administrative work, carries out rector's assignments and monitors the activities of structural units.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },

    # ── 2. YOSHLAR MASALALARI VA MA'NAVIY-MA'RIFIY ISHLAR ─────────────────────
    {
        'slug':    'yoshlar-bilan-ishlash-bolimi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   201,
        'name_uz': "Yoshlar bilan ishlash bo'limi",
        'name_ru': "Отдел по работе с молодёжью",
        'name_en': "Youth Affairs Department",
        'description_uz': "Bo'lim akademiya talabalarining ijtimoiy faolligini oshirish, ularni ijodiy va kasbiy rivojlantirishga ko'maklashish, yoshlar siyosatini hayotga tatbiq etish bilan shug'ullanadi.",
        'description_ru': "Отдел занимается повышением социальной активности студентов академии, содействием их творческому и профессиональному развитию, реализацией молодёжной политики.",
        'description_en': "The department works on increasing the social activity of academy students, assisting their creative and professional development, and implementing youth policy.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'talabalar-turar-joyi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   202,
        'name_uz': "Talabalar turar joyi",
        'name_ru': "Студенческое общежитие",
        'name_en': "Student Dormitory",
        'description_uz': "Talabalar turar joyi akademiya talabalariga qulay yashash sharoitini ta'minlaydi, yotoqxonada tartib-intizomni saqlaydi va talabalarning kundalik ehtiyojlarini qondirish uchun xizmat ko'rsatadi.",
        'description_ru': "Студенческое общежитие обеспечивает студентам академии комфортные условия проживания, поддерживает порядок и дисциплину в общежитии и оказывает услуги для удовлетворения повседневных нужд студентов.",
        'description_en': "The student dormitory provides comfortable living conditions for academy students, maintains order and discipline in the dormitory, and provides services to meet students' daily needs.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'psixolog',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   203,
        'name_uz': "Psixolog",
        'name_ru': "Психолог",
        'name_en': "Psychologist",
        'description_uz': "Akademiya psixologi talabalar va xodimlarga psixologik yordam ko'rsatadi, stress va qiyinchiliklarni yengishga ko'maklashadi, sog'lom psixologik muhitni shakllantiradi.",
        'description_ru': "Психолог академии оказывает психологическую помощь студентам и сотрудникам, помогает справляться со стрессом и трудностями, формирует здоровую психологическую среду.",
        'description_en': "The academy psychologist provides psychological assistance to students and staff, helps cope with stress and difficulties, and forms a healthy psychological environment.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'sport-klubi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   204,
        'name_uz': "Sport klubi",
        'name_ru': "Спортивный клуб",
        'name_en': "Sports Club",
        'description_uz': "Akademiya sport klubi talabalar va xodimlarning jismoniy faolligini oshirish, sport musobaqalarini tashkil etish va sport bo'limlari faoliyatini muvofiqlashtirish uchun xizmat qiladi.",
        'description_ru': "Спортивный клуб академии служит для повышения физической активности студентов и сотрудников, организации спортивных соревнований и координации деятельности спортивных секций.",
        'description_en': "The academy sports club serves to increase the physical activity of students and staff, organise sports competitions and coordinate the activities of sports sections.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },

    # ── 3. O'QUV ISHLARI BO'YICHA ─────────────────────────────────────────────
    {
        'slug':    'oquv-uslubiy-bolim',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   301,
        'name_uz': "O'quv-uslubiy bo'lim",
        'name_ru': "Учебно-методический отдел",
        'name_en': "Educational and Methodological Department",
        'description_uz': "O'quv-uslubiy bo'lim ta'lim jarayonini tashkil etish, o'quv dasturlari va rejalarini ishlab chiqish, o'quv-uslubiy ta'minotni nazorat qilish bilan shug'ullanadi.",
        'description_ru': "Учебно-методический отдел занимается организацией учебного процесса, разработкой учебных программ и планов, контролем учебно-методического обеспечения.",
        'description_en': "The Educational and Methodological Department is engaged in organising the educational process, developing curricula and plans, and monitoring educational and methodological support.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'raqamli-talim-texnologiyalari-markazi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   302,
        'name_uz': "Raqamli ta'lim texnologiyalari markazi",
        'name_ru': "Центр цифровых образовательных технологий",
        'name_en': "Centre for Digital Educational Technologies",
        'description_uz': "Markaz ta'lim jarayoniga zamonaviy raqamli texnologiyalarni joriy etish, onlayn ta'lim platformalarini rivojlantirish va o'qituvchilarni raqamli kompetensiyalar bo'yicha o'qitish bilan shug'ullanadi.",
        'description_ru': "Центр занимается внедрением современных цифровых технологий в учебный процесс, развитием платформ онлайн-обучения и обучением преподавателей цифровым компетенциям.",
        'description_en': "The centre is engaged in introducing modern digital technologies into the educational process, developing online learning platforms, and training teachers in digital competencies.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'sport-va-parasport-turlari-tashkilot',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   303,
        'name_uz': "Sport va parasport turlari",
        'name_ru': "Виды спорта и параспорта",
        'name_en': "Sports and Parasports",
        'description_uz': "Bo'lim akademiyada o'qitiladigan sport va parasport yo'nalishlarini muvofiqlashtiradi, musobaqalar taqvimini tuzadi, sport natijalari monitoringini olib boradi.",
        'description_ru': "Отдел координирует спортивные и параспортивные направления, преподаваемые в академии, составляет календарь соревнований, ведёт мониторинг спортивных результатов.",
        'description_en': "The department coordinates sports and parasports disciplines taught at the academy, draws up a competition calendar, and monitors sports results.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },

    # ── 4. ILMIY ISHLAR VA INNOVATSIYALAR ─────────────────────────────────────
    {
        'slug':    'ilmiy-tadqiqotlar',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   401,
        'name_uz': "Ilmiy tadqiqotlar",
        'name_ru': "Научные исследования",
        'name_en': "Scientific Research",
        'description_uz': "Bo'lim akademiya professor-o'qituvchilari va tadqiqotchilarining ilmiy izlanishlarini muvofiqlashtiradi, ilmiy loyihalar, grantlar va nashrlarga ko'maklashadi.",
        'description_ru': "Отдел координирует научные исследования профессорско-преподавательского состава и исследователей академии, содействует научным проектам, грантам и публикациям.",
        'description_en': "The department coordinates scientific research of academic faculty and researchers, facilitates scientific projects, grants and publications.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'xalqaro-hamkorlik',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   402,
        'name_uz': "Xalqaro hamkorlik",
        'name_ru': "Международное сотрудничество",
        'name_en': "International Cooperation",
        'description_uz': "Bo'lim xorijiy universitetlar, sport tashkilotlari va xalqaro tuzilmalar bilan hamkorlik bitimlarini tuzish, talabalar va o'qituvchilar almashinuvini tashkil etish bilan shug'ullanadi.",
        'description_ru': "Отдел занимается заключением договоров о сотрудничестве с зарубежными университетами, спортивными организациями и международными структурами, организацией обмена студентами и преподавателями.",
        'description_en': "The department is engaged in concluding cooperation agreements with foreign universities, sports organisations and international structures, and organising student and teacher exchange.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'iqtidorli-talabalar-ilmiy-faoliyati',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   403,
        'name_uz': "Iqtidorli talabalarning ilmiy faoliyati",
        'name_ru': "Научная деятельность одарённых студентов",
        'name_en': "Scientific Activity of Talented Students",
        'description_uz': "Bo'lim iqtidorli talabalarni ilmiy tadqiqotlarga jalb etish, ularning konferensiyalar, olimpiadalar va ilmiy musobaqalardagi ishtirokini tashkil etish bilan shug'ullanadi.",
        'description_ru': "Отдел занимается вовлечением талантливых студентов в научные исследования, организацией их участия в конференциях, олимпиадах и научных конкурсах.",
        'description_en': "The department engages talented students in scientific research and organises their participation in conferences, olympiads and scientific competitions.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },

    # ── 5. AKADEMIYA HUZURIDAGI TASHKILOTLAR ──────────────────────────────────
    {
        'slug':    'mutaxassislarni-qayta-tayyorlash-instituti',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   501,
        'name_uz': "Jismoniy tarbiya va sport bo'yicha mutaxassislarni qayta tayyorlash va malakasini oshirish instituti",
        'name_ru': "Институт переподготовки и повышения квалификации специалистов по физической культуре и спорту",
        'name_en': "Institute for Retraining and Advanced Training of Physical Culture and Sports Specialists",
        'description_uz': "Institut jismoniy tarbiya va sport sohasida ishlayotgan mutaxassislarning malakasini oshirish va qayta tayyorlash bo'yicha ixtisoslashtirilgan ta'lim muassasasi hisoblanadi.",
        'description_ru': "Институт является специализированным учебным заведением по повышению квалификации и переподготовке специалистов в области физической культуры и спорта.",
        'description_en': "The Institute is a specialised educational institution for advanced training and retraining of specialists in the field of physical culture and sports.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'ilmiy-tadqiqot-instituti',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   502,
        'name_uz': "Jismoniy tarbiya va sport ilmiy-tadqiqot instituti",
        'name_ru': "Научно-исследовательский институт физической культуры и спорта",
        'name_en': "Research Institute of Physical Culture and Sports",
        'description_uz': "Institut jismoniy tarbiya va sport sohasida fundamental va amaliy ilmiy tadqiqotlar olib boradi, sport fani rivojiga hissa qo'shadi.",
        'description_ru': "Институт проводит фундаментальные и прикладные научные исследования в области физической культуры и спорта, вносит вклад в развитие спортивной науки.",
        'description_en': "The Institute conducts fundamental and applied scientific research in the field of physical culture and sports, contributing to the development of sports science.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'davlat-sport-ilmiy-amaliy-markazi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   503,
        'name_uz': "Davlat sport ilmiy-amaliy markazi",
        'name_ru': "Государственный научно-практический центр спорта",
        'name_en': "State Sports Scientific and Practical Centre",
        'description_uz': "Markaz sport sohasidagi ilmiy-amaliy tadqiqotlarni amalga oshiradi, sportchilar tayyorlash metodologiyasini ishlab chiqadi va sport tibbiyoti xizmatlarini ko'rsatadi.",
        'description_ru': "Центр осуществляет научно-практические исследования в области спорта, разрабатывает методологию подготовки спортсменов и оказывает услуги спортивной медицины.",
        'description_en': "The Centre conducts scientific and practical research in the field of sports, develops methodologies for athlete training, and provides sports medicine services.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'ozbekiston-tarixi-va-xorijiy-tillar-markazi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   504,
        'name_uz': "O'zbekiston tarixi va xorijiy tillarni o'qitish markazi",
        'name_ru': "Центр преподавания истории Узбекистана и иностранных языков",
        'name_en': "Centre for Teaching Uzbekistan History and Foreign Languages",
        'description_uz': "Markaz O'zbekiston tarixi va xorijiy tillarni o'qitishni tashkil etadi, o'quv materiallarini ishlab chiqadi va til kompetensiyalarini rivojlantirishga ko'maklashadi.",
        'description_ru': "Центр организует преподавание истории Узбекистана и иностранных языков, разрабатывает учебные материалы и содействует развитию языковых компетенций.",
        'description_en': "The Centre organises the teaching of Uzbekistan history and foreign languages, develops teaching materials, and assists in developing language competencies.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'axborot-kutubxona-markazi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   505,
        'name_uz': "Axborot-kutubxona markazi",
        'name_ru': "Информационно-библиотечный центр",
        'name_en': "Information and Library Centre",
        'description_uz': "Markaz akademiya talabalar va xodimlarini o'quv, ilmiy va badiiy adabiyotlar bilan ta'minlaydi, elektron resurslar bazasini boshqaradi va axborot xizmatlarini ko'rsatadi.",
        'description_ru': "Центр обеспечивает студентов и сотрудников академии учебной, научной и художественной литературой, управляет базой электронных ресурсов и оказывает информационные услуги.",
        'description_en': "The Centre provides academy students and staff with educational, scientific and fiction literature, manages the electronic resources database, and provides information services.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },

    # ── 6. MARKAZ VA BO'LIMLAR (13 ta) ────────────────────────────────────────
    {
        'slug':    'reja-moliya-sektori',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   601,
        'name_uz': "Reja-moliya sektori",
        'name_ru': "Планово-финансовый сектор",
        'name_en': "Planning and Finance Sector",
        'description_uz': "Sektor akademiyaning yillik moliyaviy rejalarini tuzadi, byudjet mablag'laridan samarali foydalanishni nazorat qiladi va moliyaviy hisobotlarni tayyorlaydi.",
        'description_ru': "Сектор составляет годовые финансовые планы академии, контролирует эффективное использование бюджетных средств и подготавливает финансовую отчётность.",
        'description_en': "The sector draws up annual financial plans of the academy, monitors the effective use of budget funds and prepares financial reports.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'buxgalteriya',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   602,
        'name_uz': "Buxgalteriya",
        'name_ru': "Бухгалтерия",
        'name_en': "Accounting Department",
        'description_uz': "Buxgalteriya bo'limi akademiyaning moliyaviy-xo'jalik operatsiyalarini hisobga oladi, ish haqi hisob-kitoblarini amalga oshiradi va soliq hamda moliyaviy hisobotlarni taqdim etadi.",
        'description_ru': "Бухгалтерия учитывает финансово-хозяйственные операции академии, осуществляет расчёт заработной платы и представляет налоговую и финансовую отчётность.",
        'description_en': "The accounting department records financial and economic operations of the academy, processes payroll calculations, and submits tax and financial reports.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'kadrlar-bolimi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   603,
        'name_uz': "Kadrlar bo'limi",
        'name_ru': "Отдел кадров",
        'name_en': "Human Resources Department",
        'description_uz': "Kadrlar bo'limi xodimlarni ishga qabul qilish, mehnat shartnomalari tuzish, kadrlar bazasini yuritish va xodimlarning kasbiy rivojlanishini tashkil etish bilan shug'ullanadi.",
        'description_ru': "Отдел кадров занимается приёмом на работу, заключением трудовых договоров, ведением кадровой базы данных и организацией профессионального развития сотрудников.",
        'description_en': "The HR department is engaged in recruitment, concluding employment contracts, maintaining the personnel database and organising professional development of employees.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'yuriskonsult',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   604,
        'name_uz': "Yuriskonsult",
        'name_ru': "Юрисконсульт",
        'name_en': "Legal Counsel",
        'description_uz': "Yuriskonsult akademiyaning huquqiy faoliyatini ta'minlaydi, shartnomalar bo'yicha huquqiy ekspertiza o'tkazadi, me'yoriy hujjatlarni ishlab chiqishda ishtirok etadi.",
        'description_ru': "Юрисконсульт обеспечивает правовую деятельность академии, проводит правовую экспертизу договоров, участвует в разработке нормативных документов.",
        'description_en': "The Legal Counsel ensures the legal activities of the academy, conducts legal review of contracts, and participates in the development of regulatory documents.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'devxona-va-arxiv',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   605,
        'name_uz': "Devxona va arxiv",
        'name_ru': "Делопроизводство и архив",
        'name_en': "Records Management and Archive",
        'description_uz': "Bo'lim kiruvchi va chiquvchi hujjatlarni qayd qiladi, arxiv fondini saqlaydi va boshqaradi, hujjat aylanmasini tartibga soladi.",
        'description_ru': "Отдел регистрирует входящие и исходящие документы, хранит и управляет архивным фондом, регулирует документооборот.",
        'description_en': "The department registers incoming and outgoing documents, stores and manages the archival fund, and regulates document circulation.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'xavfsizlik-va-mudofaa-bolimi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   606,
        'name_uz': "Xavfsizlik va mudofaa bo'limi",
        'name_ru': "Отдел безопасности и гражданской обороны",
        'name_en': "Security and Civil Defence Department",
        'description_uz': "Bo'lim akademiya hududida xavfsizlik tartibini ta'minlaydi, favqulodda holatlarga tayyorgarlikni tashkil etadi va ichki nazorat tizimini yuritadi.",
        'description_ru': "Отдел обеспечивает режим безопасности на территории академии, организует подготовку к чрезвычайным ситуациям и ведёт систему внутреннего контроля.",
        'description_en': "The department ensures the security regime on academy grounds, organises preparedness for emergencies, and maintains the internal control system.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'axborot-texnologiyalari-bolimi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   607,
        'name_uz': "Axborot texnologiyalari bo'limi",
        'name_ru': "Отдел информационных технологий",
        'name_en': "Information Technologies Department",
        'description_uz': "Bo'lim akademiyaning kompyuter va tarmoq infratuzilmasini boshqaradi, dasturiy ta'minotni yangilaydi, kiberxavfsizlikni ta'minlaydi.",
        'description_ru': "Отдел управляет компьютерной и сетевой инфраструктурой академии, обновляет программное обеспечение, обеспечивает кибербезопасность.",
        'description_en': "The department manages the computer and network infrastructure of the academy, updates software, and ensures cybersecurity.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'moddiy-texnik-taminot-bolimi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   608,
        'name_uz': "Moddiy-texnik ta'minot bo'limi",
        'name_ru': "Отдел материально-технического обеспечения",
        'name_en': "Material and Technical Supply Department",
        'description_uz': "Bo'lim akademiyaning moddiy-texnik ehtiyojlarini qondiradi, xarid jarayonlarini tashkil etadi va ombor xo'jaligini yuritadi.",
        'description_ru': "Отдел удовлетворяет материально-технические потребности академии, организует процессы закупок и ведёт складское хозяйство.",
        'description_en': "The department meets the material and technical needs of the academy, organises procurement processes, and manages warehouse operations.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'xojalik-bolimi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   609,
        'name_uz': "Xo'jalik bo'limi",
        'name_ru': "Хозяйственный отдел",
        'name_en': "Facilities Department",
        'description_uz': "Bo'lim akademiya binolari va inshootlarini texnik jihatdan saqlash, sanitar-gigiyena normalarga rioya etilishini nazorat qilish va kommunal xizmatlarni ta'minlash bilan shug'ullanadi.",
        'description_ru': "Отдел занимается техническим содержанием зданий и сооружений академии, контролем соблюдения санитарно-гигиенических норм и обеспечением коммунальных услуг.",
        'description_en': "The department is engaged in the technical maintenance of academy buildings and structures, monitoring compliance with sanitary and hygiene standards, and providing utility services.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'press-xizmat',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   610,
        'name_uz': "Press-xizmat",
        'name_ru': "Пресс-служба",
        'name_en': "Press Service",
        'description_uz': "Press-xizmat akademiyaning ommaviy axborot vositalari bilan aloqasini tashkil etadi, yangiliklar tarqatadi, ijtimoiy tarmoqlardagi rasmiy sahifalarni boshqaradi.",
        'description_ru': "Пресс-служба организует взаимодействие академии со средствами массовой информации, распространяет новости, управляет официальными страницами в социальных сетях.",
        'description_en': "The press service organises the academy's interaction with mass media, distributes news, and manages official social media pages.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'ichki-nazorat-bolimi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   611,
        'name_uz': "Ichki nazorat bo'limi",
        'name_ru': "Отдел внутреннего контроля",
        'name_en': "Internal Control Department",
        'description_uz': "Bo'lim akademiya bo'limlari faoliyatini audit qiladi, moliyaviy intizomni nazorat qiladi va qonun hujjatlariga rioya etilishini ta'minlaydi.",
        'description_ru': "Отдел проводит аудит деятельности подразделений академии, контролирует финансовую дисциплину и обеспечивает соблюдение законодательства.",
        'description_en': "The department audits the activities of academy units, monitors financial discipline, and ensures compliance with legislation.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'sifat-nazorat-bolimi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   612,
        'name_uz': "Ta'lim sifatini nazorat qilish bo'limi",
        'name_ru': "Отдел контроля качества образования",
        'name_en': "Educational Quality Control Department",
        'description_uz': "Bo'lim ta'lim jarayonining sifatini baholaydi, akkreditatsiya va reytingga tayyorgarlikni tashkil etadi, o'qituvchilar faoliyatini monitoring qiladi.",
        'description_ru': "Отдел оценивает качество образовательного процесса, организует подготовку к аккредитации и рейтингу, ведёт мониторинг деятельности преподавателей.",
        'description_en': "The department assesses the quality of the educational process, organises preparation for accreditation and ranking, and monitors teacher performance.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
    {
        'slug':    'sport-inshootlari-bolimi',
        'type':    FakultetKafedra.TASHKILOT,
        'order':   613,
        'name_uz': "Sport inshootlari bo'limi",
        'name_ru': "Отдел спортивных сооружений",
        'name_en': "Sports Facilities Department",
        'description_uz': "Bo'lim akademiya sport inshootlari — stadion, sport zallari, basseyn va boshqa obyektlarni texnik jihatdan saqlash va foydalanishni tashkil etadi.",
        'description_ru': "Отдел организует техническое содержание и эксплуатацию спортивных сооружений академии — стадиона, спортивных залов, бассейна и других объектов.",
        'description_en': "The department organises the technical maintenance and operation of academy sports facilities — stadium, sports halls, swimming pool and other facilities.",
        'about_uz': "", 'about_ru': "", 'about_en': "",
        'decree_info': "", 'phone': "", 'email': "", 'link': "",
        'sport_types_uz': "", 'sport_types_ru': "", 'sport_types_en': "",
        'bachelor_subjects_uz': "", 'bachelor_subjects_ru': "", 'bachelor_subjects_en': "",
        'master_subjects_uz': "", 'master_subjects_ru': "", 'master_subjects_en': "",
    },
]


class Command(BaseCommand):
    help = "Akademiya tuzilmasi bo'limlari ma'lumotlarini to'ldiradi (idempotent)"

    def add_arguments(self, parser):
        parser.add_argument('--clear', action='store_true', help="Avval o'chirib, qaytadan yozadi")

    def handle(self, *args, **options):
        if options['clear']:
            slugs = [d['slug'] for d in DATA]
            n = FakultetKafedra.objects.filter(slug__in=slugs).delete()[0]
            self.stdout.write(self.style.WARNING(f"O'chirildi: {n} ta yozuv"))

        created = updated = 0
        for data in DATA:
            slug = data.pop('slug')
            obj, is_new = FakultetKafedra.objects.update_or_create(
                slug=slug,
                defaults=data,
            )
            data['slug'] = slug
            if is_new:
                created += 1
            else:
                updated += 1
            label = '[+]' if is_new else '[~]'
            self.stdout.write(f"  {label} {obj.name_uz}")

        self.stdout.write(self.style.SUCCESS(
            f"\nNatija: {created} yangi, {updated} yangilandi. Jami {len(DATA)} ta."
        ))
