# Generated by Django 5.2.1 on 2026-04-27 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AxborotSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Band raqami')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'db_table': 'axborot_section',
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='AxborotVazifa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('body_uz', models.TextField(verbose_name='Matn (Uz)')),
                ('body_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('body_en', models.TextField(blank=True, verbose_name='Matn (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='axborot.axborotsection', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'db_table': 'axborot_vazifa',
                'ordering': ['order'],
            },
        ),
    ]
