from django.urls import path
from .views import (
    ForeignProfessorReviewListAPIView,
    PartnerOrganizationListAPIView,
    InternationalPostListAPIView,
    InternationalPostDetailAPIView,
    InternationalPostDetailBySlugAPIView,
    InternationalRatingListAPIView,
    InternationalRatingDetailAPIView,
    InternationalDeptConfigAPIView,
    MemorandumStatListAPIView,
    InternationalPostRecordViewAPIView,
    InternationalRatingRecordViewAPIView,
    AkademikAlmashinuvListAPIView,
    XalqaroReytingBolimListAPIView,
    XorijlikProfessorListAPIView,
    XorijlikProfessorDetailAPIView,
)

urlpatterns = [
    path('foreign-reviews/',                            ForeignProfessorReviewListAPIView.as_view(),  name='foreign-reviews-list'),
    path('partner-organizations/',                      PartnerOrganizationListAPIView.as_view(),     name='international-partners'),
    path('international-posts/slug/<slug:slug>/',       InternationalPostDetailBySlugAPIView.as_view(),  name='intl-post-detail-slug'),
    path('international-posts/<uuid:pk>/view/',         InternationalPostRecordViewAPIView.as_view(),    name='intl-post-record-view'),
    path('international-posts/<uuid:pk>/',              InternationalPostDetailAPIView.as_view(),        name='intl-post-detail'),
    path('international-posts/',                        InternationalPostListAPIView.as_view(),          name='international-posts'),
    path('international-ratings/<uuid:pk>/view/',       InternationalRatingRecordViewAPIView.as_view(), name='intl-rating-record-view'),
    path('international-ratings/<slug:slug>/',          InternationalRatingDetailAPIView.as_view(),   name='international-ratings-detail'),
    path('international-ratings/',                      InternationalRatingListAPIView.as_view(),     name='international-ratings-list'),
    path('dept-config/',                                InternationalDeptConfigAPIView.as_view(),     name='international-dept-config'),
    path('memorandum-stats/',                           MemorandumStatListAPIView.as_view(),          name='memorandum-stats'),
    path('akademik-almashinuv/',                        AkademikAlmashinuvListAPIView.as_view(),       name='akademik-almashinuv'),
    path('xalqaro-reyting-bolimlar/',                   XalqaroReytingBolimListAPIView.as_view(),      name='xalqaro-reyting-bolimlar'),
    path('xorijlik-professorlar/',                      XorijlikProfessorListAPIView.as_view(),         name='xorijlik-professorlar-list'),
    path('xorijlik-professorlar/<uuid:pk>/',            XorijlikProfessorDetailAPIView.as_view(),       name='xorijlik-professorlar-detail'),
]
