# Generated by Django 5.1.4 on 2026-04-10 12:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message="To'g'ri email manzil kiriting. Namuna: info@ozdsa.uz", regex='^[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}$')], verbose_name='Rasmiy Pochta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('address_uz', models.CharField(max_length=300, verbose_name='Manzil (Uz)')),
                ('address_ru', models.CharField(blank=True, max_length=300, verbose_name='Manzil (Ru)')),
                ('address_en', models.CharField(blank=True, max_length=300, verbose_name='Manzil (En)')),
            ],
            options={
                'verbose_name': 'Aloqa sozlamasi',
                'verbose_name_plural': 'Aloqa sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title', models.CharField(max_length=255, verbose_name='video nomi')),
                ('video_url', models.URLField(blank=True, help_text="MP4 yoki WebM formatidagi to'g'ridan-to'g'ri havolani kiriting", max_length=500, null=True, verbose_name='Video URLi')),
                ('video_file', models.FileField(blank=True, help_text="MP4 yoki WebM formatidagi video faylni yuklang (URL bo'lmasa)", null=True, upload_to='hero_videos/files/', verbose_name='Video fayli')),
                ('poster_image', models.ImageField(help_text='Video yuborilmaguncha joylab turiladigan rasm (poster)', upload_to='hero_videos/posters/', verbose_name='Poster rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Asosiy page video',
                'verbose_name_plural': 'Asosiy page videolar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavbarCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Nomi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (En)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug (URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatilsinmi?")),
                ('direct_url', models.CharField(blank=True, help_text="Children bo'lmasa ishlatiladi. Masalan: /news yoki https://hemis.uz. Bo'sh qolsa slug'dan avtomatik yasaladi.", max_length=500, verbose_name="To'g'ridan URL (ixtiyoriy)")),
            ],
            options={
                'verbose_name': "Navbar bo'limi",
                'verbose_name_plural': "Navbar bo'limlari",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to='partners/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, verbose_name='Sayt manzili (URL)')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatilsinmi?")),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlarimiz',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PresidentQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('quote_uz', models.TextField(verbose_name='Iqtibos (Uz)')),
                ('quote_ru', models.TextField(blank=True, verbose_name='Iqtibos (Ru)')),
                ('quote_en', models.TextField(blank=True, verbose_name='Iqtibos (En)')),
                ('author', models.CharField(default='Sh. Mirziyoyev', max_length=150, verbose_name='Muallif')),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rinsinmi?")),
            ],
            options={
                'verbose_name': 'Prezident iqtibosi',
                'verbose_name_plural': 'Prezident iqtiboslari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter')], max_length=50, unique=True, verbose_name='Ijtimoiy tarmoq turi')),
                ('url', models.URLField(verbose_name='Manzil (URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rinsinmi?")),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
            },
        ),
        migrations.CreateModel(
            name='NavbarSubItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Nomi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (En)')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug (URL)')),
                ('page_type', models.CharField(choices=[('static', 'Statik sahifa (matn)'), ('redirect', "Yo'naltirish (URL)")], default='static', max_length=10, verbose_name='Sahifa turi')),
                ('content_uz', models.TextField(blank=True, verbose_name='Sahifa matni (Uz)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Sahifa matni (Ru)')),
                ('content_en', models.TextField(blank=True, verbose_name='Sahifa matni (En)')),
                ('redirect_url', models.CharField(blank=True, help_text='Masalan: /api/news/ yoki https://hemis.uz', max_length=500, verbose_name="Yo'naltirish manzili (URL)")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatilsinmi?")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.navbarcategory', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Navbar sahifasi',
                'verbose_name_plural': 'Navbar sahifalari',
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LinkBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (En)')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Havola (URL)')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Fayl (PDF)')),
                ('block_type', models.CharField(choices=[('file-list', "Fayllar ro'yxati"), ('useful-links', 'Foydali havolalar')], default='useful-links', max_length=20, verbose_name='Blok turi')),
                ('navbar_items', models.ManyToManyField(blank=True, related_name='%(class)s_items', to='pages.navbarsubitem', verbose_name='Navbar sahifalari')),
            ],
            options={
                'verbose_name': 'Havola bloki',
                'verbose_name_plural': 'Havola bloklari',
                'db_table': 'pages_link_block',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='pages_link__is_acti_0e8ff9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('title_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif (En)')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Havola (URL)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('block_type', models.CharField(choices=[('hero', 'Hero banner'), ('rich-text', 'Matn (HTML)'), ('stats', 'Statistikalar'), ('gallery', 'Galereya'), ('quote', 'Iqtibos'), ('table', 'Jadval'), ('timeline', "Vaqt chizig'i")], default='rich-text', max_length=20, verbose_name='Blok turi')),
                ('json_data', models.JSONField(blank=True, help_text="Stats, table, timeline uchun strukturali JSON. Rich-text/hero/gallery da bo'sh qoldiring.", null=True, verbose_name="JSON ma'lumot")),
                ('tags', models.ManyToManyField(blank=True, related_name='content_blocks', to='common.tag', verbose_name='Taglar')),
                ('navbar_items', models.ManyToManyField(blank=True, related_name='%(class)s_items', to='pages.navbarsubitem', verbose_name='Navbar sahifalari')),
            ],
            options={
                'verbose_name': 'Kontent bloki',
                'verbose_name_plural': 'Kontent bloklari',
                'db_table': 'pages_content_block',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='pages_conte_is_acti_8ee1ca_idx')],
            },
        ),
    ]
