# Generated by Django 5.1.4 on 2026-03-24 09:57

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message="To'g'ri email manzil kiriting. Namuna: info@ozdsa.uz", regex='^[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}$')], verbose_name='Rasmiy Pochta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('address_uz', models.CharField(max_length=300, verbose_name='Manzil (Uz)')),
                ('address_ru', models.CharField(blank=True, max_length=300, verbose_name='Manzil (Ru)')),
                ('address_en', models.CharField(blank=True, max_length=300, verbose_name='Manzil (En)')),
            ],
            options={
                'verbose_name': 'Aloqa sozlamasi',
                'verbose_name_plural': 'Aloqa sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='PresidentQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('quote_uz', models.TextField(verbose_name='Iqtibos (Uz)')),
                ('quote_ru', models.TextField(blank=True, verbose_name='Iqtibos (Ru)')),
                ('quote_en', models.TextField(blank=True, verbose_name='Iqtibos (En)')),
                ('author', models.CharField(default='Sh. Mirziyoyev', max_length=150, verbose_name='Muallif')),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rinsinmi?")),
            ],
            options={
                'verbose_name': 'Prezident iqtibosi',
                'verbose_name_plural': 'Prezident iqtiboslari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter')], max_length=50, unique=True, verbose_name='Ijtimoiy tarmoq turi')),
                ('url', models.URLField(verbose_name='Manzil (URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rinsinmi?")),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
            },
        ),
    ]
