# Generated by Django 5.1.4 on 2026-03-24 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Nomi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (En)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug (URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatilsinmi?")),
            ],
            options={
                'verbose_name': "Navbar bo'limi",
                'verbose_name_plural': "Navbar bo'limlari",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavbarSubItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Nomi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Nomi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Nomi (En)')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug (URL)')),
                ('page_type', models.CharField(choices=[('static', 'Statik sahifa (matn)'), ('redirect', "Yo'naltirish (URL)")], default='static', max_length=10, verbose_name='Sahifa turi')),
                ('content_uz', models.TextField(blank=True, verbose_name='Sahifa matni (Uz)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Sahifa matni (Ru)')),
                ('content_en', models.TextField(blank=True, verbose_name='Sahifa matni (En)')),
                ('redirect_url', models.CharField(blank=True, help_text='Masalan: /api/v1/news/news/ yoki https://hemis.uz', max_length=500, verbose_name="Yo'naltirish manzili (URL)")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name="Ko'rsatilsinmi?")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.navbarcategory', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Navbar sahifasi',
                'verbose_name_plural': 'Navbar sahifalari',
                'ordering': ['category__order', 'order'],
            },
        ),
    ]
