# Generated by Django 5.1.4 on 2026-04-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero banner'), ('rich-text', 'Matn (HTML)'), ('stats', 'Statistikalar'), ('gallery', 'Galereya'), ('quote', 'Iqtibos'), ('table', 'Jadval'), ('timeline', "Vaqt chizig'i")], default='rich-text', max_length=20, verbose_name='Blok turi'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='json_data',
            field=models.JSONField(blank=True, help_text="Stats, table, timeline uchun strukturali JSON. Rich-text/hero/gallery da bo'sh qoldiring.", null=True, verbose_name="JSON ma'lumot"),
        ),
        migrations.AddField(
            model_name='linkblock',
            name='block_type',
            field=models.CharField(choices=[('file-list', "Fayllar ro'yxati"), ('useful-links', 'Foydali havolalar')], default='useful-links', max_length=20, verbose_name='Blok turi'),
        ),
    ]
