# Generated by Django 5.1.4 on 2026-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_fix_redirect_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herovideo',
            name='poster_image',
            field=models.FileField(help_text='Video yuborilmaguncha joylab turiladigan rasm (poster)', upload_to='hero_videos/posters/', verbose_name='Poster rasmi'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.FileField(upload_to='partners/', verbose_name='Logo'),
        ),
    ]
