# Generated by Django 5.1.4 on 2026-04-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_navbar_items_m2m'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentblock',
            new_name='pages_conte_is_acti_8ee1ca_idx',
            old_name='pages_conte_is_acti_m2m_idx',
        ),
        migrations.RenameIndex(
            model_name='linkblock',
            new_name='pages_link__is_acti_0e8ff9_idx',
            old_name='pages_linkb_is_acti_m2m_idx',
        ),
        migrations.AddField(
            model_name='herovideo',
            name='video_file',
            field=models.FileField(blank=True, help_text="MP4 yoki WebM formatidagi video faylni yuklang (URL bo'lmasa)", null=True, upload_to='hero_videos/files/', verbose_name='Video fayli'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='navbar_items',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_items', to='pages.navbarsubitem', verbose_name='Navbar sahifalari'),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='video_url',
            field=models.URLField(blank=True, help_text="MP4 yoki WebM formatidagi to'g'ridan-to'g'ri havolani kiriting", max_length=500, null=True, verbose_name='Video URLi'),
        ),
        migrations.AlterField(
            model_name='linkblock',
            name='navbar_items',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_items', to='pages.navbarsubitem', verbose_name='Navbar sahifalari'),
        ),
    ]
