# Generated by Django 5.1.4 on 2026-03-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, verbose_name='Sayt manzili (URL)'),
        ),
    ]
