# Generated by Django 5.1.4 on 2026-03-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_partner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarcategory',
            name='direct_url',
            field=models.CharField(blank=True, help_text="Children bo'lmasa ishlatiladi. Masalan: /news yoki https://hemis.uz. Bo'sh qolsa slug'dan avtomatik yasaladi.", max_length=500, verbose_name="To'g'ridan URL (ixtiyoriy)"),
        ),
    ]
