# Generated by Django 5.1.4 on 2026-03-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_add_direct_url_to_navbarcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='video nomi')),
                ('video_url', models.URLField(help_text="MP4 yoki WebM formatidagi to'g'ridan-to'g'ri havolani kiriting", max_length=500, verbose_name='Video URLi')),
                ('poster_image', models.ImageField(help_text='Video yuborilmaguncha joylab turiladigan rasm (poster)', upload_to='hero_videos/posters/', verbose_name='Poster rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asosiy page video',
                'verbose_name_plural': 'Asosiy page videolar',
                'ordering': ['-created_at'],
            },
        ),
    ]
