# Generated by Django 5.1.4 on 2026-03-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_herovideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarsubitem',
            name='redirect_url',
            field=models.CharField(blank=True, help_text='Masalan: /api/news/ yoki https://hemis.uz', max_length=500, verbose_name="Yo'naltirish manzili (URL)"),
        ),
    ]
