# Generated by Django 5.1.4 on 2026-03-31 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('pages', '0007_staff_navbar_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('title_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Tavsif (En)')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Havola (URL)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('navbar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='pages.navbarsubitem', verbose_name='Navbar sahifasi')),
                ('tags', models.ManyToManyField(blank=True, related_name='content_blocks', to='common.tag', verbose_name='Taglar')),
            ],
            options={
                'verbose_name': 'Kontent bloki',
                'verbose_name_plural': 'Kontent bloklari',
                'db_table': 'pages_content_block',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['navbar_item', 'is_active', 'order'], name='pages_conte_navbar__9c6f14_idx')],
            },
        ),
        migrations.CreateModel(
            name='LinkBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=500, verbose_name='Sarlavha (En)')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Havola (URL)')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Fayl (PDF)')),
                ('navbar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_items', to='pages.navbarsubitem', verbose_name='Navbar sahifasi')),
            ],
            options={
                'verbose_name': 'Havola bloki',
                'verbose_name_plural': 'Havola bloklari',
                'db_table': 'pages_link_block',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['navbar_item', 'is_active', 'order'], name='pages_link__navbar__6111c1_idx')],
            },
        ),
    ]
