# Generated by Django 5.2.1 on 2026-04-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_orgnode_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgnode',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
    ]
