# Generated by Django 5.2.1 on 2026-04-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_orgnode_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsubitem',
            name='direct_url',
            field=models.CharField(blank=True, help_text="Bo'sh qolsa /page/{slug} ishlatiladi. Masalan: /news yoki https://hemis.uz", max_length=500, verbose_name='Maxsus URL (ixtiyoriy)'),
        ),
    ]
