# Generated by Django 5.2.1 on 2026-04-27 12:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_navbarsubitem_add_direct_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rekvizit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('org_name_uz', models.CharField(max_length=300, verbose_name="To'liq nomi (Uz)")),
                ('org_name_ru', models.CharField(blank=True, max_length=300, verbose_name="To'liq nomi (Ru)")),
                ('org_name_en', models.CharField(blank=True, max_length=300, verbose_name="To'liq nomi (En)")),
                ('org_short_name', models.CharField(max_length=50, verbose_name='Qisqartilgan nomi')),
                ('email_1', models.EmailField(max_length=254, verbose_name='Email 1')),
                ('email_2', models.EmailField(blank=True, max_length=254, verbose_name='Email 2')),
                ('phone_1', models.CharField(max_length=30, verbose_name='Telefon 1')),
                ('phone_2', models.CharField(blank=True, max_length=30, verbose_name='Telefon 2')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Pochta indeksi')),
                ('address_uz', models.CharField(max_length=500, verbose_name='Manzil (Uz)')),
                ('address_ru', models.CharField(blank=True, max_length=500, verbose_name='Manzil (Ru)')),
                ('address_en', models.CharField(blank=True, max_length=500, verbose_name='Manzil (En)')),
            ],
            options={
                'verbose_name': 'Rekvizit',
                'verbose_name_plural': 'Rekvizitlar',
                'db_table': 'pages_rekvizit',
            },
        ),
    ]
