# Generated by Django 5.2.1 on 2026-04-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_orgnode_rename_name_to_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgnode',
            options={'ordering': ['order', 'title_uz'], 'verbose_name': 'Tashkiliy tugun', 'verbose_name_plural': 'Tashkiliy tuzilma'},
        ),
    ]
