# Generated by Django 5.2.1 on 2026-04-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_orgnode_options'),
        ('pages', '0012_orgsection_orgnode_section_fields'),
    ]

    operations = [
    ]
