# Generated by Django 5.2.1 on 2026-04-28 05:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_orgsection_created_at_alter_orgsection_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAcademy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('description_uz', models.TextField(verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (En)')),
            ],
            options={
                'verbose_name': 'Akademiya haqida',
                'verbose_name_plural': 'Akademiya haqida',
                'db_table': 'pages_about_academy',
            },
        ),
        migrations.CreateModel(
            name='AboutAcademyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('program_type', models.CharField(choices=[('bachelor', 'Bakalavriat'), ('master', 'Magistratura')], max_length=10, verbose_name='Dastur turi')),
                ('direction_uz', models.CharField(max_length=300, verbose_name="Yo'nalish (Uz)")),
                ('direction_ru', models.CharField(blank=True, max_length=300, verbose_name="Yo'nalish (Ru)")),
                ('direction_en', models.CharField(blank=True, max_length=300, verbose_name="Yo'nalish (En)")),
                ('profession_uz', models.CharField(max_length=300, verbose_name='Mutaxassislik (Uz)')),
                ('profession_ru', models.CharField(blank=True, max_length=300, verbose_name='Mutaxassislik (Ru)')),
                ('profession_en', models.CharField(blank=True, max_length=300, verbose_name='Mutaxassislik (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='pages.aboutacademy', verbose_name='Akademiya haqida')),
            ],
            options={
                'verbose_name': "Ta'lim dasturi",
                'verbose_name_plural': "Ta'lim dasturlari",
                'db_table': 'pages_about_academy_program',
                'ordering': ['program_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AboutAcademySection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('key', models.CharField(help_text='API javobida ishlatiladi, masalan: goals, tasks, system, partners', max_length=50, verbose_name='Kalit')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.aboutacademy', verbose_name='Akademiya haqida')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'db_table': 'pages_about_academy_section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutAcademySectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('text_uz', models.TextField(verbose_name='Matn (Uz)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('text_en', models.TextField(blank=True, verbose_name='Matn (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.aboutacademysection', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elementlar',
                'db_table': 'pages_about_academy_section_item',
                'ordering': ['order'],
            },
        ),
    ]
