# Generated by Django 5.2.1 on 2026-04-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_about_academy'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutacademy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_academy/', verbose_name='Asosiy rasm'),
        ),
        migrations.AddField(
            model_name='aboutacademy',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='about_academy/', verbose_name='Logo'),
        ),
    ]
