# Generated by Django 5.2.1 on 2026-04-29 09:58

import django.db.models.deletion
import domains.pages.models.about_academy
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_add_logo_image_to_about_academy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAcademyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to=domains.pages.models.about_academy.about_academy_gallery_upload, verbose_name='Rasm')),
                ('caption_uz', models.CharField(blank=True, max_length=300, verbose_name='Izoh (Uz)')),
                ('caption_ru', models.CharField(blank=True, max_length=300, verbose_name='Izoh (Ru)')),
                ('caption_en', models.CharField(blank=True, max_length=300, verbose_name='Izoh (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.aboutacademy', verbose_name='Akademiya haqida')),
            ],
            options={
                'verbose_name': 'Gallery rasmi',
                'verbose_name_plural': 'Gallery rasmlari',
                'db_table': 'pages_about_academy_image',
                'ordering': ['order'],
            },
        ),
    ]
