# Generated by Django 5.2.1 on 2026-04-30 05:13

import domains.pages.models.markaz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_markaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaktivxizmat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='interaktivxizmat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='markaz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=domains.pages.models.markaz.markaz_image_upload, verbose_name='Rasm'),
        ),
    ]
