# Generated by Django 5.2.1 on 2026-05-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_interaktivxizmat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgnode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='org_nodes/', verbose_name='Rasm'),
        ),
    ]
