# Generated by Django 5.2.1 on 2026-05-01 11:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_orgnode_add_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (En)')),
                ('address_uz', models.TextField(verbose_name='Manzil (Uz)')),
                ('address_ru', models.TextField(blank=True, verbose_name='Manzil (Ru)')),
                ('address_en', models.TextField(blank=True, verbose_name='Manzil (En)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Aloqa joyi',
                'verbose_name_plural': 'Aloqa joylari',
                'db_table': 'pages_contact_location',
                'ordering': ['order'],
            },
        ),
    ]
