# Generated by Django 5.2.1 on 2026-05-07 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_ilmiybolim_ilmiybolimyonalish'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkademiyaMissiya',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('description_uz', models.TextField(blank=True, verbose_name='Missiya matni (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Missiya matni (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Missiya matni (En)')),
            ],
            options={
                'verbose_name': 'Akademiya missiyasi',
                'verbose_name_plural': 'Akademiya missiyasi',
                'db_table': 'pages_akademiya_missiya',
            },
        ),
        migrations.AlterField(
            model_name='ilmiybolim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='ilmiybolim',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ilmiybolim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='ilmiybolimyonalish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='ilmiybolimyonalish',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ilmiybolimyonalish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.CreateModel(
            name='AkademiyaMissiyaYonalish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('text_uz', models.TextField(verbose_name="Yo'nalish matni (Uz)")),
                ('text_ru', models.TextField(blank=True, verbose_name="Yo'nalish matni (Ru)")),
                ('text_en', models.TextField(blank=True, verbose_name="Yo'nalish matni (En)")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('missiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yonalishlar', to='pages.akademiyamissiya')),
            ],
            options={
                'verbose_name': "Missiya yo'nalishi",
                'verbose_name_plural': "Missiya yo'nalishlari",
                'db_table': 'pages_akademiya_missiya_yonalish',
                'ordering': ['order'],
            },
        ),
    ]
