# Generated by Django 5.2.1 on 2026-05-07 09:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_akademiyamissiya_alter_ilmiybolim_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkblock',
            name='document_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='documents/%Y/%m/', verbose_name='Fayl (PDF)'),
        ),
    ]
