# Generated by Django 5.2.1 on 2026-05-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_linkblock_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkblock',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Fayl (PDF)'),
        ),
    ]
