# Generated by Django 5.2.1 on 2026-05-07 10:42

import django.db.models.deletion
import domains.pages.models.savol_javob
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alter_linkblock_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavolJavobCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Nomi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Nomi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Nomi (En)')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=64, verbose_name='Icon nomi (ixtiyoriy)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Savol-javob kategoriyasi',
                'verbose_name_plural': 'Savol-javob kategoriyalari',
                'db_table': 'pages_savol_javob_category',
                'ordering': ['order', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='SavolJavob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('question_uz', models.CharField(max_length=500, verbose_name='Savol (Uz)')),
                ('question_ru', models.CharField(blank=True, max_length=500, verbose_name='Savol (Ru)')),
                ('question_en', models.CharField(blank=True, max_length=500, verbose_name='Savol (En)')),
                ('answer_uz', models.TextField(verbose_name='Javob (Uz)')),
                ('answer_ru', models.TextField(blank=True, verbose_name='Javob (Ru)')),
                ('answer_en', models.TextField(blank=True, verbose_name='Javob (En)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=domains.pages.models.savol_javob.savol_javob_image_upload, verbose_name='Rasm (ixtiyoriy)')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tepada chiqsin?')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savol_javoblar', to='pages.savoljavobcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Savol-javob',
                'verbose_name_plural': 'Savol-javoblar',
                'db_table': 'pages_savol_javob',
                'ordering': ['-is_featured', 'order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='pages_savol_is_acti_aa5e43_idx')],
            },
        ),
    ]
