# Generated by Django 5.2.1 on 2026-05-14 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_homepage_haqida'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsubitem',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif (En)'),
        ),
        migrations.AddField(
            model_name='navbarsubitem',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif (Ru)'),
        ),
        migrations.AddField(
            model_name='navbarsubitem',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif (Uz)'),
        ),
        migrations.AlterField(
            model_name='homepagehaqida',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='homepagehaqida',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homepagehaqida',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='homepagehaqidarasm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='homepagehaqidarasm',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homepagehaqidarasm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
    ]
