# Generated by Django 5.2.1 on 2026-05-16 05:05

import domains.pages.models.markaz
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_iqtidorli_talabalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutacademy',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='about_academy/', verbose_name='Asosiy rasm (En)'),
        ),
        migrations.AddField(
            model_name='aboutacademy',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='about_academy/', verbose_name='Asosiy rasm (Ru)'),
        ),
        migrations.AddField(
            model_name='herovideo',
            name='poster_image_en',
            field=models.FileField(blank=True, null=True, upload_to='hero_videos/posters/', verbose_name='Poster rasmi (En)'),
        ),
        migrations.AddField(
            model_name='herovideo',
            name='poster_image_ru',
            field=models.FileField(blank=True, null=True, upload_to='hero_videos/posters/', verbose_name='Poster rasmi (Ru)'),
        ),
        migrations.AddField(
            model_name='iqtidorlitalabalar',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='iqtidorli/', verbose_name='Rasm (En)'),
        ),
        migrations.AddField(
            model_name='iqtidorlitalabalar',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='iqtidorli/', verbose_name='Rasm (Ru)'),
        ),
        migrations.AddField(
            model_name='markaz',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=domains.pages.models.markaz.markaz_image_upload, verbose_name='Rasm (En)'),
        ),
        migrations.AddField(
            model_name='markaz',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=domains.pages.models.markaz.markaz_image_upload, verbose_name='Rasm (Ru)'),
        ),
        migrations.AlterField(
            model_name='aboutacademy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_academy/', verbose_name='Asosiy rasm (Uz)'),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='poster_image',
            field=models.FileField(help_text='Video yuborilmaguncha joylab turiladigan rasm (poster)', upload_to='hero_videos/posters/', verbose_name='Poster rasmi (Uz)'),
        ),
        migrations.AlterField(
            model_name='iqtidorlitalabalar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='iqtidorlitalabalar',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iqtidorlitalabalar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='iqtidorli/', verbose_name='Rasm (Uz)'),
        ),
        migrations.AlterField(
            model_name='iqtidorlitalabalar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='iqtidorlivazifa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='iqtidorlivazifa',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iqtidorlivazifa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='kampusxizmati',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='kampusxizmati',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kampusxizmati',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
        migrations.AlterField(
            model_name='markaz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=domains.pages.models.markaz.markaz_image_upload, verbose_name='Rasm (Uz)'),
        ),
    ]
