# Generated by Django 5.2.1 on 2026-05-18 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_markaz_goals_functions_xodim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kampusxizmati',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100, verbose_name="Icon nomi (lucide, rasm yo'q bo'lsa)"),
        ),
        migrations.AlterField(
            model_name='markazxodim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='markazxodim',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='markazxodim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt'),
        ),
    ]
