# Generated by Django 5.2.1 on 2026-05-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_alter_kampusxizmati_icon_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markaz',
            name='description_en',
            field=models.TextField(blank=True, verbose_name="Bo'lim haqida ma'lumot (En)"),
        ),
        migrations.AlterField(
            model_name='markaz',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name="Bo'lim haqida ma'lumot (Ru)"),
        ),
        migrations.AlterField(
            model_name='markaz',
            name='description_uz',
            field=models.TextField(blank=True, verbose_name="Bo'lim haqida ma'lumot (Uz)"),
        ),
        migrations.AlterField(
            model_name='markaz',
            name='goals_en',
            field=models.TextField(blank=True, verbose_name="Bo'lim maqsad va vazifalari (En)"),
        ),
        migrations.AlterField(
            model_name='markaz',
            name='goals_ru',
            field=models.TextField(blank=True, verbose_name="Bo'lim maqsad va vazifalari (Ru)"),
        ),
        migrations.AlterField(
            model_name='markaz',
            name='goals_uz',
            field=models.TextField(blank=True, verbose_name="Bo'lim maqsad va vazifalari (Uz)"),
        ),
    ]
