# Generated by Django 5.1.4 on 2026-03-31 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0008_contentblock_linkblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignProfessorReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ismi sharifi')),
                ('position_uz', models.CharField(blank=True, max_length=255, verbose_name='Lavozimi (Uz)')),
                ('position_ru', models.CharField(blank=True, max_length=255, verbose_name='Lavozimi (Ru)')),
                ('position_en', models.CharField(blank=True, max_length=255, verbose_name='Lavozimi (En)')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Mamlakat')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='foreign_professors/%Y/%m/', verbose_name='Foto')),
                ('review_uz', models.TextField(verbose_name='Fikr (Uz)')),
                ('review_ru', models.TextField(blank=True, verbose_name='Fikr (Ru)')),
                ('review_en', models.TextField(blank=True, verbose_name='Fikr (En)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('navbar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreign_reviews', to='pages.navbarsubitem', verbose_name='Navbar sahifasi')),
            ],
            options={
                'verbose_name': 'Xorijlik professor fikri',
                'verbose_name_plural': 'Xorijlik professorlar fikrlari',
                'db_table': 'international_foreign_professor_review',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['navbar_item', 'is_active', 'order'], name='internation_navbar__7af7bf_idx')],
            },
        ),
    ]
