# Generated by Django 5.1.4 on 2026-04-21 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('post_type', models.CharField(choices=[('announcement', "E'lon"), ('news', 'Yangilik'), ('training', 'Xorijda malaka oshirish')], default='news', max_length=20, verbose_name='Tur')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (En)')),
                ('content_uz', models.TextField(verbose_name='Matn (Uz)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('content_en', models.TextField(blank=True, verbose_name='Matn (En)')),
                ('image', models.ImageField(blank=True, upload_to='international/posts/%Y/%m/', verbose_name='Rasm')),
                ('date', models.DateField(verbose_name='Sana')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': "Xalqaro bo'lim xabari",
                'verbose_name_plural': "Xalqaro bo'lim xabarlari",
                'db_table': 'international_post',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('partner_type', models.CharField(choices=[('foreign', 'Xorijiy hamkor'), ('domestic', "O'zbekiston tashkiloti")], default='foreign', max_length=20, verbose_name='Hamkor turi')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Nomi (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Nomi (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Nomi (En)')),
                ('country_uz', models.CharField(blank=True, max_length=100, verbose_name='Mamlakat (Uz)')),
                ('country_ru', models.CharField(blank=True, max_length=100, verbose_name='Mamlakat (Ru)')),
                ('country_en', models.CharField(blank=True, max_length=100, verbose_name='Mamlakat (En)')),
                ('logo', models.ImageField(blank=True, upload_to='international/logos/%Y/', verbose_name='Logo')),
                ('image', models.ImageField(blank=True, upload_to='international/partners/%Y/', verbose_name='Rasm')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Hamkor tashkilot',
                'verbose_name_plural': 'Hamkor tashkilotlar',
                'db_table': 'international_partner_organization',
                'ordering': ['partner_type', 'order'],
            },
        ),
    ]
