# Generated by Django 5.1.4 on 2026-04-22 11:44

import django.db.models.deletion
import domains.international.models.post_image
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0002_add_partner_and_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalPostImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to=domains.international.models.post_image.post_image_upload, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='international.internationalpost', verbose_name="E'lon")),
            ],
            options={
                'verbose_name': "E'lon rasmi",
                'verbose_name_plural': "E'lon rasmlari",
                'db_table': 'international_post_image',
                'ordering': ['order'],
            },
        ),
    ]
