# Generated by Django 5.1.4 on 2026-04-23 13:19

import domains.international.models.post_image
import domains.international.models.rating
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0005_alter_internationalrating_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignprofessorreview',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='foreign_professors/%Y/%m/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='internationalpost',
            name='image',
            field=models.FileField(blank=True, upload_to='international/posts/%Y/%m/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='internationalpostimage',
            name='image',
            field=models.FileField(upload_to=domains.international.models.post_image.post_image_upload, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='internationalrating',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=domains.international.models.rating.rating_cover_upload, verbose_name='Muqova rasmi'),
        ),
        migrations.AlterField(
            model_name='internationalratingimage',
            name='image',
            field=models.FileField(upload_to=domains.international.models.rating.rating_image_upload, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='image',
            field=models.FileField(blank=True, upload_to='international/partners/%Y/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='logo',
            field=models.FileField(blank=True, upload_to='international/logos/%Y/', verbose_name='Logo'),
        ),
    ]
