# Generated by Django 5.1.4 on 2026-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0006_alter_foreignprofessorreview_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (En)')),
            ],
            options={
                'verbose_name': 'Hamkor sahifasi konfiguratsiyasi',
                'verbose_name_plural': 'Hamkor sahifasi konfiguratsiyasi',
                'db_table': 'international_partner_page_config',
            },
        ),
    ]
