# Generated by Django 5.1.4 on 2026-04-25 06:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0007_add_partner_page_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalDeptConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name_uz', models.CharField(blank=True, max_length=300, verbose_name="Bo'lim boshlig'i (Uz)")),
                ('head_name_ru', models.CharField(blank=True, max_length=300, verbose_name="Bo'lim boshlig'i (Ru)")),
                ('head_name_en', models.CharField(blank=True, max_length=300, verbose_name="Bo'lim boshlig'i (En)")),
                ('head_position_uz', models.CharField(blank=True, max_length=300, verbose_name='Lavozimi (Uz)')),
                ('head_position_ru', models.CharField(blank=True, max_length=300, verbose_name='Lavozimi (Ru)')),
                ('head_position_en', models.CharField(blank=True, max_length=300, verbose_name='Lavozimi (En)')),
                ('head_working_hours', models.CharField(blank=True, max_length=200, verbose_name='Qabul kunlari')),
                ('head_phone', models.CharField(blank=True, max_length=200, verbose_name='Telefon')),
                ('head_email', models.CharField(blank=True, max_length=300, verbose_name='E-mail')),
                ('head_photo', models.FileField(blank=True, null=True, upload_to='international/dept_head/', verbose_name="Boshlig' rasmi")),
                ('tasks_uz', models.TextField(blank=True, help_text='Har bir vazifani yangi satrga yozing', verbose_name='Vazifalari (Uz)')),
                ('tasks_ru', models.TextField(blank=True, verbose_name='Vazifalari (Ru)')),
                ('tasks_en', models.TextField(blank=True, verbose_name='Vazifalari (En)')),
            ],
            options={
                'verbose_name': "Xalqaro bo'lim konfiguratsiyasi",
                'verbose_name_plural': "Xalqaro bo'lim konfiguratsiyasi",
                'db_table': 'international_dept_config',
            },
        ),
        migrations.CreateModel(
            name='MemorandumStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('organization_uz', models.CharField(max_length=500, verbose_name='Tashkilot nomi (Uz)')),
                ('organization_ru', models.CharField(blank=True, max_length=500, verbose_name='Tashkilot nomi (Ru)')),
                ('organization_en', models.CharField(blank=True, max_length=500, verbose_name='Tashkilot nomi (En)')),
                ('foreign_count', models.PositiveIntegerField(default=0, verbose_name='Xorijiy memorandumlar soni')),
                ('domestic_count', models.PositiveIntegerField(default=0, verbose_name='Mahalliy memorandumlar soni')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Memorandum statistikasi',
                'verbose_name_plural': 'Memorandumlar statistikasi',
                'db_table': 'international_memorandum_stat',
                'ordering': ['order'],
            },
        ),
    ]
