# Generated by Django 5.1.4 on 2026-04-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0009_initial_dept_and_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalpost',
            name='post_type',
            field=models.CharField(choices=[('announcement', "E'lon"), ('news', 'Yangilik'), ('training', 'Xorijda malaka oshirish'), ('academic_exchange', 'Akademik almashinuv')], default='news', max_length=20, verbose_name='Tur'),
        ),
    ]
