# Generated by Django 5.2.1 on 2026-04-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0011_internationaldeptconfig_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerorganization',
            name='image',
            field=models.FileField(blank=True, upload_to='partners/images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='partnerorganization',
            name='logo',
            field=models.FileField(blank=True, upload_to='partners/logos/', verbose_name='Logo'),
        ),
    ]
