# Generated by Django 5.2.1 on 2026-05-01 05:28

import django.db.models.deletion
import domains.international.models.almashinuv
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0012_partner_upload_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkademikAlmashinuv',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title_uz', models.CharField(max_length=400, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=400, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=400, verbose_name='Sarlavha (En)')),
                ('body_uz', models.TextField(verbose_name='Matn (Uz)')),
                ('body_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('body_en', models.TextField(blank=True, verbose_name='Matn (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': "Akademik almashinuv bo'limi",
                'verbose_name_plural': "Akademik almashinuv bo'limlari",
                'db_table': 'international_akademik_almashinuv',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AkademikAlmashinuvRasm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to=domains.international.models.almashinuv.almashinuv_image_upload, verbose_name='Rasm')),
                ('caption_uz', models.CharField(blank=True, max_length=300, verbose_name='Izoh (Uz)')),
                ('caption_ru', models.CharField(blank=True, max_length=300, verbose_name='Izoh (Ru)')),
                ('caption_en', models.CharField(blank=True, max_length=300, verbose_name='Izoh (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='international.akademikalmashinuv', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Almashinuv rasmi',
                'verbose_name_plural': 'Almashinuv rasmlari',
                'db_table': 'international_akademik_almashinuv_rasm',
                'ordering': ['order'],
            },
        ),
    ]
