# Generated by Django 5.2.1 on 2026-05-01 05:43

import domains.international.models.xalqaro_reyting
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0013_akademik_almashinuv'),
    ]

    operations = [
        migrations.CreateModel(
            name='XalqaroReytingBolim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('bolim_type', models.CharField(choices=[('sport', 'Sportchilar reytingi'), ('professor', "Professor-o'qituvchilar reytingi")], max_length=20, verbose_name="Bo'lim turi")),
                ('title_uz', models.CharField(max_length=400, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=400, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=400, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (En)')),
                ('image', models.ImageField(blank=True, null=True, upload_to=domains.international.models.xalqaro_reyting.xalqaro_reyting_image_upload, verbose_name='Rasm (screenshot)')),
                ('link', models.URLField(blank=True, verbose_name='Tashqi havola (URL)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': "Xalqaro reyting bo'limi",
                'verbose_name_plural': "Xalqaro reyting bo'limlari",
                'db_table': 'international_xalqaro_reyting_bolim',
                'ordering': ['bolim_type', 'order'],
            },
        ),
    ]
