# Generated by Django 5.2.1 on 2026-05-01 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0014_xalqaro_reyting_bolim'),
    ]

    operations = [
        migrations.CreateModel(
            name='XorijlikProfessor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ismi sharifi')),
                ('photo', models.FileField(blank=True, null=True, upload_to='xorijlik_professorlar/%Y/%m/', verbose_name='Rasm')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Mamlakat')),
                ('from_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qachondan (yil)')),
                ('bio_uz', models.TextField(blank=True, verbose_name='Bio / Tavsif (Uz)')),
                ('bio_ru', models.TextField(blank=True, verbose_name='Bio / Tavsif (Ru)')),
                ('bio_en', models.TextField(blank=True, verbose_name='Bio / Tavsif (En)')),
                ('education_uz', models.TextField(blank=True, verbose_name="Ma'lumoti (Uz)")),
                ('education_ru', models.TextField(blank=True, verbose_name="Ma'lumoti (Ru)")),
                ('education_en', models.TextField(blank=True, verbose_name="Ma'lumoti (En)")),
                ('specialty_uz', models.CharField(blank=True, max_length=300, verbose_name="Ma'lumoti bo'yicha mutaxassisligi (Uz)")),
                ('specialty_ru', models.CharField(blank=True, max_length=300, verbose_name="Ma'lumoti bo'yicha mutaxassisligi (Ru)")),
                ('specialty_en', models.CharField(blank=True, max_length=300, verbose_name="Ma'lumoti bo'yicha mutaxassisligi (En)")),
                ('academic_degree_uz', models.CharField(blank=True, max_length=200, verbose_name='Ilmiy darajasi (Uz)')),
                ('academic_degree_ru', models.CharField(blank=True, max_length=200, verbose_name='Ilmiy darajasi (Ru)')),
                ('academic_degree_en', models.CharField(blank=True, max_length=200, verbose_name='Ilmiy darajasi (En)')),
                ('academic_title_uz', models.CharField(blank=True, max_length=200, verbose_name='Ilmiy unvoni (Uz)')),
                ('academic_title_ru', models.CharField(blank=True, max_length=200, verbose_name='Ilmiy unvoni (Ru)')),
                ('academic_title_en', models.CharField(blank=True, max_length=200, verbose_name='Ilmiy unvoni (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': "Xorijlik professor-o'qituvchi",
                'verbose_name_plural': "Xorijlik professor-o'qituvchilar",
                'db_table': 'international_xorijlik_professor',
                'ordering': ['order'],
            },
        ),
    ]
