# Generated by Django 5.2.1 on 2026-05-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0015_xorijlikprofessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, unique=True, verbose_name='Slug'),
        ),
    ]
