# Generated by Django 5.2.1 on 2026-05-03 11:22

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    InternationalPost = apps.get_model('international', 'InternationalPost')
    seen = set()
    for post in InternationalPost.objects.all().order_by('date', 'id'):
        base = slugify(post.title_uz, allow_unicode=True) or str(post.id)
        slug = base
        n = 1
        while slug in seen:
            slug = f'{base}-{n}'
            n += 1
        seen.add(slug)
        post.slug = slug
        post.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0015_xorijlikprofessor'),
    ]

    operations = [
        # 1. Avval unique=False bilan qo'shamiz
        migrations.AddField(
            model_name='internationalpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, unique=False, verbose_name='Slug'),
        ),
        # 2. Mavjud qatorlarga slug generate qilamiz
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
        # 3. Endi unique=True qilamiz
        migrations.AlterField(
            model_name='internationalpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, unique=True, verbose_name='Slug'),
        ),
    ]
