# Generated by Django 5.2.1 on 2026-05-03 12:47

import django.db.models.deletion
import domains.international.models.xalqaro_reyting
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0018_add_slug_to_reyting_va_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='XalqaroReytingBolimRasm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.ImageField(upload_to=domains.international.models.xalqaro_reyting.xalqaro_reyting_rasm_upload, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='international.xalqaroreytingbolim', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': "Reyting bo'limi rasmi",
                'verbose_name_plural': "Reyting bo'limi rasmlari",
                'db_table': 'international_xalqaro_reyting_bolim_rasm',
                'ordering': ['order'],
            },
        ),
    ]
