# Generated by Django 5.2.1 on 2026-05-16 05:05

import domains.international.models.xalqaro_reyting
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0019_add_xalqaro_reyting_bolim_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalpost',
            name='image_en',
            field=models.FileField(blank=True, null=True, upload_to='international/posts/%Y/%m/', verbose_name='Rasm (En)'),
        ),
        migrations.AddField(
            model_name='internationalpost',
            name='image_ru',
            field=models.FileField(blank=True, null=True, upload_to='international/posts/%Y/%m/', verbose_name='Rasm (Ru)'),
        ),
        migrations.AddField(
            model_name='xalqaroreytingbolim',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=domains.international.models.xalqaro_reyting.xalqaro_reyting_image_upload, verbose_name='Rasm (En)'),
        ),
        migrations.AddField(
            model_name='xalqaroreytingbolim',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=domains.international.models.xalqaro_reyting.xalqaro_reyting_image_upload, verbose_name='Rasm (Ru)'),
        ),
        migrations.AlterField(
            model_name='internationalpost',
            name='image',
            field=models.FileField(blank=True, upload_to='international/posts/%Y/%m/', verbose_name='Rasm (Uz)'),
        ),
        migrations.AlterField(
            model_name='xalqaroreytingbolim',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=domains.international.models.xalqaro_reyting.xalqaro_reyting_image_upload, verbose_name='Rasm (Uz)'),
        ),
    ]
