# Generated by Django 5.2.1 on 2026-05-17 10:46

import domains.international.models.almashinuv
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0021_working_hours_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='akademikalmashinuvrasm',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=domains.international.models.almashinuv.almashinuv_image_upload, verbose_name='Rasm (En)'),
        ),
        migrations.AddField(
            model_name='akademikalmashinuvrasm',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=domains.international.models.almashinuv.almashinuv_image_upload, verbose_name='Rasm (Ru)'),
        ),
        migrations.AlterField(
            model_name='akademikalmashinuvrasm',
            name='image',
            field=models.ImageField(upload_to=domains.international.models.almashinuv.almashinuv_image_upload, verbose_name='Rasm (Uz)'),
        ),
    ]
