# Generated by Django 5.2.1 on 2026-05-18 07:21

import django.db.models.deletion
import domains.international.models.national_rating
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0022_almashinuv_rasm_image_ru_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('name_uz', models.CharField(max_length=300, verbose_name='Nomi (Uz)')),
                ('name_ru', models.CharField(blank=True, max_length=300, verbose_name='Nomi (Ru)')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='Nomi (En)')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Sarlavha (Uz)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (Ru)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Sarlavha (En)')),
                ('description_uz', models.TextField(verbose_name='Matn (Uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Matn (Ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Matn (En)')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Milliy reyting',
                'verbose_name_plural': 'Milliy reytinglar',
                'db_table': 'national_rating',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NationalRatingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('image', models.FileField(upload_to=domains.international.models.national_rating.national_rating_image_upload, verbose_name='Rasm')),
                ('alt_uz', models.CharField(blank=True, max_length=300, verbose_name='Alt (Uz)')),
                ('alt_ru', models.CharField(blank=True, max_length=300, verbose_name='Alt (Ru)')),
                ('alt_en', models.CharField(blank=True, max_length=300, verbose_name='Alt (En)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='international.nationalrating', verbose_name='Milliy reyting')),
            ],
            options={
                'verbose_name': 'Milliy reyting rasmi',
                'verbose_name_plural': 'Milliy reyting rasmlari',
                'db_table': 'national_rating_image',
                'ordering': ['order'],
            },
        ),
    ]
