# Generated by Django 5.2.1 on 2026-05-19 06:51

import domains.international.models.national_rating
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0024_rename_image_add_image_ru_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalratingimage',
            name='image_uz',
            field=models.FileField(upload_to=domains.international.models.national_rating.national_rating_image_upload, verbose_name='Rasm (Uz)'),
        ),
    ]
