# Generated by Django 5.2.1 on 2026-06-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0026_studyinuzbekistanconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyinuzbekistanconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
